/*
 * CloudKey Service Account API
 * 卡密管理系统 - 服务账号 SDK
 *
 * The version of the OpenAPI document: 1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.ezzzi_y.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.github.ezzzi_y.CloudKeyJSON;

/**
 * AdjustBalanceResult
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-22T22:12:40.541788+08:00[Asia/Shanghai]", comments = "Generator version: 7.24.0")
public class AdjustBalanceResult {
  public static final String SERIALIZED_NAME_BEFORE_AMOUNT = "before_amount";
  @SerializedName(SERIALIZED_NAME_BEFORE_AMOUNT)
  @javax.annotation.Nullable
  private Long beforeAmount;

  public static final String SERIALIZED_NAME_AFTER_AMOUNT = "after_amount";
  @SerializedName(SERIALIZED_NAME_AFTER_AMOUNT)
  @javax.annotation.Nullable
  private Long afterAmount;

  public AdjustBalanceResult() {
  }

  public AdjustBalanceResult beforeAmount(@javax.annotation.Nullable Long beforeAmount) {
    this.beforeAmount = beforeAmount;
    return this;
  }

  /**
   * 调整前余额
   * @return beforeAmount
   */
  @javax.annotation.Nullable
  public Long getBeforeAmount() {
    return beforeAmount;
  }

  public void setBeforeAmount(@javax.annotation.Nullable Long beforeAmount) {
    this.beforeAmount = beforeAmount;
  }


  public AdjustBalanceResult afterAmount(@javax.annotation.Nullable Long afterAmount) {
    this.afterAmount = afterAmount;
    return this;
  }

  /**
   * 调整后余额
   * @return afterAmount
   */
  @javax.annotation.Nullable
  public Long getAfterAmount() {
    return afterAmount;
  }

  public void setAfterAmount(@javax.annotation.Nullable Long afterAmount) {
    this.afterAmount = afterAmount;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdjustBalanceResult adjustBalanceResult = (AdjustBalanceResult) o;
    return Objects.equals(this.beforeAmount, adjustBalanceResult.beforeAmount) &&
        Objects.equals(this.afterAmount, adjustBalanceResult.afterAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(beforeAmount, afterAmount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdjustBalanceResult {\n");
    sb.append("    beforeAmount: ").append(toIndentedString(beforeAmount)).append("\n");
    sb.append("    afterAmount: ").append(toIndentedString(afterAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("before_amount", "after_amount"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AdjustBalanceResult
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AdjustBalanceResult.openapiRequiredFields.isEmpty()) { // has required fields but CloudKeyJSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in AdjustBalanceResult is not found in the empty JSON string", AdjustBalanceResult.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AdjustBalanceResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `AdjustBalanceResult` properties. CloudKeyJSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AdjustBalanceResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AdjustBalanceResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AdjustBalanceResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AdjustBalanceResult.class));

       return (TypeAdapter<T>) new TypeAdapter<AdjustBalanceResult>() {
           @Override
           public void write(JsonWriter out, AdjustBalanceResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AdjustBalanceResult read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AdjustBalanceResult given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AdjustBalanceResult
   * @throws IOException if the JSON string is invalid with respect to AdjustBalanceResult
   */
  public static AdjustBalanceResult fromJson(String jsonString) throws IOException {
    return CloudKeyJSON.getGson().fromJson(jsonString, AdjustBalanceResult.class);
  }

  /**
   * Convert an instance of AdjustBalanceResult to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return CloudKeyJSON.getGson().toJson(this);
  }
}

