/*
 * CloudKey Service Account API
 * 卡密管理系统 - 服务账号 SDK
 *
 * The version of the OpenAPI document: 1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.ezzzi_y.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.github.ezzzi_y.CloudKeyJSON;

/**
 * BalanceLog
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-21T19:47:27.911944800+08:00[Asia/Shanghai]", comments = "Generator version: 7.24.0")
public class BalanceLog {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Long id;

  public static final String SERIALIZED_NAME_TENANT_ID = "tenant_id";
  @SerializedName(SERIALIZED_NAME_TENANT_ID)
  @javax.annotation.Nullable
  private Long tenantId;

  public static final String SERIALIZED_NAME_KEY_ID = "key_id";
  @SerializedName(SERIALIZED_NAME_KEY_ID)
  @javax.annotation.Nullable
  private Long keyId;

  public static final String SERIALIZED_NAME_KEY_ALIAS = "key_alias";
  @SerializedName(SERIALIZED_NAME_KEY_ALIAS)
  @javax.annotation.Nullable
  private String keyAlias;

  public static final String SERIALIZED_NAME_DELTA = "delta";
  @SerializedName(SERIALIZED_NAME_DELTA)
  @javax.annotation.Nullable
  private Long delta;

  public static final String SERIALIZED_NAME_BEFORE_AMOUNT = "before_amount";
  @SerializedName(SERIALIZED_NAME_BEFORE_AMOUNT)
  @javax.annotation.Nullable
  private Long beforeAmount;

  public static final String SERIALIZED_NAME_AFTER_AMOUNT = "after_amount";
  @SerializedName(SERIALIZED_NAME_AFTER_AMOUNT)
  @javax.annotation.Nullable
  private Long afterAmount;

  public static final String SERIALIZED_NAME_OPERATOR = "operator";
  @SerializedName(SERIALIZED_NAME_OPERATOR)
  @javax.annotation.Nullable
  private String operator;

  public static final String SERIALIZED_NAME_REMARK = "remark";
  @SerializedName(SERIALIZED_NAME_REMARK)
  @javax.annotation.Nullable
  private String remark;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public BalanceLog() {
  }

  public BalanceLog id(@javax.annotation.Nullable Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public Long getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Long id) {
    this.id = id;
  }


  public BalanceLog tenantId(@javax.annotation.Nullable Long tenantId) {
    this.tenantId = tenantId;
    return this;
  }

  /**
   * Get tenantId
   * @return tenantId
   */
  @javax.annotation.Nullable
  public Long getTenantId() {
    return tenantId;
  }

  public void setTenantId(@javax.annotation.Nullable Long tenantId) {
    this.tenantId = tenantId;
  }


  public BalanceLog keyId(@javax.annotation.Nullable Long keyId) {
    this.keyId = keyId;
    return this;
  }

  /**
   * Get keyId
   * @return keyId
   */
  @javax.annotation.Nullable
  public Long getKeyId() {
    return keyId;
  }

  public void setKeyId(@javax.annotation.Nullable Long keyId) {
    this.keyId = keyId;
  }


  public BalanceLog keyAlias(@javax.annotation.Nullable String keyAlias) {
    this.keyAlias = keyAlias;
    return this;
  }

  /**
   * Get keyAlias
   * @return keyAlias
   */
  @javax.annotation.Nullable
  public String getKeyAlias() {
    return keyAlias;
  }

  public void setKeyAlias(@javax.annotation.Nullable String keyAlias) {
    this.keyAlias = keyAlias;
  }


  public BalanceLog delta(@javax.annotation.Nullable Long delta) {
    this.delta = delta;
    return this;
  }

  /**
   * 变动量：正&#x3D;增加，负&#x3D;减少
   * @return delta
   */
  @javax.annotation.Nullable
  public Long getDelta() {
    return delta;
  }

  public void setDelta(@javax.annotation.Nullable Long delta) {
    this.delta = delta;
  }


  public BalanceLog beforeAmount(@javax.annotation.Nullable Long beforeAmount) {
    this.beforeAmount = beforeAmount;
    return this;
  }

  /**
   * Get beforeAmount
   * @return beforeAmount
   */
  @javax.annotation.Nullable
  public Long getBeforeAmount() {
    return beforeAmount;
  }

  public void setBeforeAmount(@javax.annotation.Nullable Long beforeAmount) {
    this.beforeAmount = beforeAmount;
  }


  public BalanceLog afterAmount(@javax.annotation.Nullable Long afterAmount) {
    this.afterAmount = afterAmount;
    return this;
  }

  /**
   * Get afterAmount
   * @return afterAmount
   */
  @javax.annotation.Nullable
  public Long getAfterAmount() {
    return afterAmount;
  }

  public void setAfterAmount(@javax.annotation.Nullable Long afterAmount) {
    this.afterAmount = afterAmount;
  }


  public BalanceLog operator(@javax.annotation.Nullable String operator) {
    this.operator = operator;
    return this;
  }

  /**
   * Get operator
   * @return operator
   */
  @javax.annotation.Nullable
  public String getOperator() {
    return operator;
  }

  public void setOperator(@javax.annotation.Nullable String operator) {
    this.operator = operator;
  }


  public BalanceLog remark(@javax.annotation.Nullable String remark) {
    this.remark = remark;
    return this;
  }

  /**
   * Get remark
   * @return remark
   */
  @javax.annotation.Nullable
  public String getRemark() {
    return remark;
  }

  public void setRemark(@javax.annotation.Nullable String remark) {
    this.remark = remark;
  }


  public BalanceLog createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BalanceLog balanceLog = (BalanceLog) o;
    return Objects.equals(this.id, balanceLog.id) &&
        Objects.equals(this.tenantId, balanceLog.tenantId) &&
        Objects.equals(this.keyId, balanceLog.keyId) &&
        Objects.equals(this.keyAlias, balanceLog.keyAlias) &&
        Objects.equals(this.delta, balanceLog.delta) &&
        Objects.equals(this.beforeAmount, balanceLog.beforeAmount) &&
        Objects.equals(this.afterAmount, balanceLog.afterAmount) &&
        Objects.equals(this.operator, balanceLog.operator) &&
        Objects.equals(this.remark, balanceLog.remark) &&
        Objects.equals(this.createdAt, balanceLog.createdAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, tenantId, keyId, keyAlias, delta, beforeAmount, afterAmount, operator, remark, createdAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BalanceLog {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    keyId: ").append(toIndentedString(keyId)).append("\n");
    sb.append("    keyAlias: ").append(toIndentedString(keyAlias)).append("\n");
    sb.append("    delta: ").append(toIndentedString(delta)).append("\n");
    sb.append("    beforeAmount: ").append(toIndentedString(beforeAmount)).append("\n");
    sb.append("    afterAmount: ").append(toIndentedString(afterAmount)).append("\n");
    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("    remark: ").append(toIndentedString(remark)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "tenant_id", "key_id", "key_alias", "delta", "before_amount", "after_amount", "operator", "remark", "created_at"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BalanceLog
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BalanceLog.openapiRequiredFields.isEmpty()) { // has required fields but CloudKeyJSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in BalanceLog is not found in the empty JSON string", BalanceLog.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BalanceLog.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `BalanceLog` properties. CloudKeyJSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("key_alias") != null && !jsonObj.get("key_alias").isJsonNull()) && !jsonObj.get("key_alias").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `key_alias` to be a primitive type in the JSON string but got `%s`", jsonObj.get("key_alias").toString()));
      }
      if ((jsonObj.get("operator") != null && !jsonObj.get("operator").isJsonNull()) && !jsonObj.get("operator").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `operator` to be a primitive type in the JSON string but got `%s`", jsonObj.get("operator").toString()));
      }
      if ((jsonObj.get("remark") != null && !jsonObj.get("remark").isJsonNull()) && !jsonObj.get("remark").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `remark` to be a primitive type in the JSON string but got `%s`", jsonObj.get("remark").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BalanceLog.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BalanceLog' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BalanceLog> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BalanceLog.class));

       return (TypeAdapter<T>) new TypeAdapter<BalanceLog>() {
           @Override
           public void write(JsonWriter out, BalanceLog value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BalanceLog read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BalanceLog given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BalanceLog
   * @throws IOException if the JSON string is invalid with respect to BalanceLog
   */
  public static BalanceLog fromJson(String jsonString) throws IOException {
    return CloudKeyJSON.getGson().fromJson(jsonString, BalanceLog.class);
  }

  /**
   * Convert an instance of BalanceLog to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return CloudKeyJSON.getGson().toJson(this);
  }
}

