/*
 * CloudKey Service Account API
 * 卡密管理系统 - 服务账号 SDK
 *
 * The version of the OpenAPI document: 1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.ezzzi_y.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.github.ezzzi_y.CloudKeyJSON;

/**
 * CreateKeyRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-21T15:39:59.098139500+08:00[Asia/Shanghai]", comments = "Generator version: 7.24.0")
public class CreateKeyRequest {
  public static final String SERIALIZED_NAME_ALIAS = "alias";
  @SerializedName(SERIALIZED_NAME_ALIAS)
  @javax.annotation.Nonnull
  private String alias;

  /**
   * Gets or Sets billingMode
   */
  @JsonAdapter(BillingModeEnum.Adapter.class)
  public enum BillingModeEnum {
    COUNT("count"),
    
    CREDIT("credit");

    private String value;

    BillingModeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static BillingModeEnum fromValue(String value) {
      for (BillingModeEnum b : BillingModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<BillingModeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final BillingModeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public BillingModeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return BillingModeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      BillingModeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_BILLING_MODE = "billing_mode";
  @SerializedName(SERIALIZED_NAME_BILLING_MODE)
  @javax.annotation.Nonnull
  private BillingModeEnum billingMode;

  public static final String SERIALIZED_NAME_INITIAL_AMOUNT = "initial_amount";
  @SerializedName(SERIALIZED_NAME_INITIAL_AMOUNT)
  @javax.annotation.Nonnull
  private Long initialAmount;

  public static final String SERIALIZED_NAME_EXPIRE_AT = "expire_at";
  @SerializedName(SERIALIZED_NAME_EXPIRE_AT)
  @javax.annotation.Nullable
  private OffsetDateTime expireAt;

  public static final String SERIALIZED_NAME_MAX_USAGE = "max_usage";
  @SerializedName(SERIALIZED_NAME_MAX_USAGE)
  @javax.annotation.Nullable
  private Long maxUsage;

  public CreateKeyRequest() {
  }

  public CreateKeyRequest alias(@javax.annotation.Nonnull String alias) {
    this.alias = alias;
    return this;
  }

  /**
   * Get alias
   * @return alias
   */
  @javax.annotation.Nonnull
  public String getAlias() {
    return alias;
  }

  public void setAlias(@javax.annotation.Nonnull String alias) {
    this.alias = alias;
  }


  public CreateKeyRequest billingMode(@javax.annotation.Nonnull BillingModeEnum billingMode) {
    this.billingMode = billingMode;
    return this;
  }

  /**
   * Get billingMode
   * @return billingMode
   */
  @javax.annotation.Nonnull
  public BillingModeEnum getBillingMode() {
    return billingMode;
  }

  public void setBillingMode(@javax.annotation.Nonnull BillingModeEnum billingMode) {
    this.billingMode = billingMode;
  }


  public CreateKeyRequest initialAmount(@javax.annotation.Nonnull Long initialAmount) {
    this.initialAmount = initialAmount;
    return this;
  }

  /**
   * Get initialAmount
   * @return initialAmount
   */
  @javax.annotation.Nonnull
  public Long getInitialAmount() {
    return initialAmount;
  }

  public void setInitialAmount(@javax.annotation.Nonnull Long initialAmount) {
    this.initialAmount = initialAmount;
  }


  public CreateKeyRequest expireAt(@javax.annotation.Nullable OffsetDateTime expireAt) {
    this.expireAt = expireAt;
    return this;
  }

  /**
   * Get expireAt
   * @return expireAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getExpireAt() {
    return expireAt;
  }

  public void setExpireAt(@javax.annotation.Nullable OffsetDateTime expireAt) {
    this.expireAt = expireAt;
  }


  public CreateKeyRequest maxUsage(@javax.annotation.Nullable Long maxUsage) {
    this.maxUsage = maxUsage;
    return this;
  }

  /**
   * Get maxUsage
   * @return maxUsage
   */
  @javax.annotation.Nullable
  public Long getMaxUsage() {
    return maxUsage;
  }

  public void setMaxUsage(@javax.annotation.Nullable Long maxUsage) {
    this.maxUsage = maxUsage;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateKeyRequest createKeyRequest = (CreateKeyRequest) o;
    return Objects.equals(this.alias, createKeyRequest.alias) &&
        Objects.equals(this.billingMode, createKeyRequest.billingMode) &&
        Objects.equals(this.initialAmount, createKeyRequest.initialAmount) &&
        Objects.equals(this.expireAt, createKeyRequest.expireAt) &&
        Objects.equals(this.maxUsage, createKeyRequest.maxUsage);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(alias, billingMode, initialAmount, expireAt, maxUsage);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateKeyRequest {\n");
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("    billingMode: ").append(toIndentedString(billingMode)).append("\n");
    sb.append("    initialAmount: ").append(toIndentedString(initialAmount)).append("\n");
    sb.append("    expireAt: ").append(toIndentedString(expireAt)).append("\n");
    sb.append("    maxUsage: ").append(toIndentedString(maxUsage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("alias", "billing_mode", "initial_amount", "expire_at", "max_usage"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("alias", "billing_mode", "initial_amount"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateKeyRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateKeyRequest.openapiRequiredFields.isEmpty()) { // has required fields but CloudKeyJSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CreateKeyRequest is not found in the empty JSON string", CreateKeyRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateKeyRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CreateKeyRequest` properties. CloudKeyJSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateKeyRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("alias").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `alias` to be a primitive type in the JSON string but got `%s`", jsonObj.get("alias").toString()));
      }
      if (!jsonObj.get("billing_mode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `billing_mode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("billing_mode").toString()));
      }
      // validate the required field `billing_mode`
      BillingModeEnum.validateJsonElement(jsonObj.get("billing_mode"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateKeyRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateKeyRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateKeyRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateKeyRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateKeyRequest>() {
           @Override
           public void write(JsonWriter out, CreateKeyRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateKeyRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateKeyRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateKeyRequest
   * @throws IOException if the JSON string is invalid with respect to CreateKeyRequest
   */
  public static CreateKeyRequest fromJson(String jsonString) throws IOException {
    return CloudKeyJSON.getGson().fromJson(jsonString, CreateKeyRequest.class);
  }

  /**
   * Convert an instance of CreateKeyRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return CloudKeyJSON.getGson().toJson(this);
  }
}

