/*
 * CloudKey API
 * 卡密管理系统 API 文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.ezzzi_y.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.github.ezzzi_y.JSON;

/**
 * HandlerCreateKeyJSON
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-20T19:01:01.615859700+08:00[Asia/Shanghai]", comments = "Generator version: 7.24.0")
public class HandlerCreateKeyJSON {
  public static final String SERIALIZED_NAME_ALIAS = "alias";
  @SerializedName(SERIALIZED_NAME_ALIAS)
  @javax.annotation.Nonnull
  private String alias;

  public static final String SERIALIZED_NAME_BILLING_MODE = "billing_mode";
  @SerializedName(SERIALIZED_NAME_BILLING_MODE)
  @javax.annotation.Nonnull
  private String billingMode;

  public static final String SERIALIZED_NAME_EXPIRE_AT = "expire_at";
  @SerializedName(SERIALIZED_NAME_EXPIRE_AT)
  @javax.annotation.Nullable
  private String expireAt;

  public static final String SERIALIZED_NAME_INITIAL_AMOUNT = "initial_amount";
  @SerializedName(SERIALIZED_NAME_INITIAL_AMOUNT)
  @javax.annotation.Nonnull
  private Integer initialAmount;

  public static final String SERIALIZED_NAME_MAX_USAGE = "max_usage";
  @SerializedName(SERIALIZED_NAME_MAX_USAGE)
  @javax.annotation.Nullable
  private Integer maxUsage;

  public HandlerCreateKeyJSON() {
  }

  public HandlerCreateKeyJSON alias(@javax.annotation.Nonnull String alias) {
    this.alias = alias;
    return this;
  }

  /**
   * Get alias
   * @return alias
   */
  @javax.annotation.Nonnull
  public String getAlias() {
    return alias;
  }

  public void setAlias(@javax.annotation.Nonnull String alias) {
    this.alias = alias;
  }


  public HandlerCreateKeyJSON billingMode(@javax.annotation.Nonnull String billingMode) {
    this.billingMode = billingMode;
    return this;
  }

  /**
   * Get billingMode
   * @return billingMode
   */
  @javax.annotation.Nonnull
  public String getBillingMode() {
    return billingMode;
  }

  public void setBillingMode(@javax.annotation.Nonnull String billingMode) {
    this.billingMode = billingMode;
  }


  public HandlerCreateKeyJSON expireAt(@javax.annotation.Nullable String expireAt) {
    this.expireAt = expireAt;
    return this;
  }

  /**
   * Get expireAt
   * @return expireAt
   */
  @javax.annotation.Nullable
  public String getExpireAt() {
    return expireAt;
  }

  public void setExpireAt(@javax.annotation.Nullable String expireAt) {
    this.expireAt = expireAt;
  }


  public HandlerCreateKeyJSON initialAmount(@javax.annotation.Nonnull Integer initialAmount) {
    this.initialAmount = initialAmount;
    return this;
  }

  /**
   * Get initialAmount
   * @return initialAmount
   */
  @javax.annotation.Nonnull
  public Integer getInitialAmount() {
    return initialAmount;
  }

  public void setInitialAmount(@javax.annotation.Nonnull Integer initialAmount) {
    this.initialAmount = initialAmount;
  }


  public HandlerCreateKeyJSON maxUsage(@javax.annotation.Nullable Integer maxUsage) {
    this.maxUsage = maxUsage;
    return this;
  }

  /**
   * Get maxUsage
   * @return maxUsage
   */
  @javax.annotation.Nullable
  public Integer getMaxUsage() {
    return maxUsage;
  }

  public void setMaxUsage(@javax.annotation.Nullable Integer maxUsage) {
    this.maxUsage = maxUsage;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HandlerCreateKeyJSON handlerCreateKeyJSON = (HandlerCreateKeyJSON) o;
    return Objects.equals(this.alias, handlerCreateKeyJSON.alias) &&
        Objects.equals(this.billingMode, handlerCreateKeyJSON.billingMode) &&
        Objects.equals(this.expireAt, handlerCreateKeyJSON.expireAt) &&
        Objects.equals(this.initialAmount, handlerCreateKeyJSON.initialAmount) &&
        Objects.equals(this.maxUsage, handlerCreateKeyJSON.maxUsage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alias, billingMode, expireAt, initialAmount, maxUsage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HandlerCreateKeyJSON {\n");
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("    billingMode: ").append(toIndentedString(billingMode)).append("\n");
    sb.append("    expireAt: ").append(toIndentedString(expireAt)).append("\n");
    sb.append("    initialAmount: ").append(toIndentedString(initialAmount)).append("\n");
    sb.append("    maxUsage: ").append(toIndentedString(maxUsage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("alias", "billing_mode", "expire_at", "initial_amount", "max_usage"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("alias", "billing_mode", "initial_amount"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to HandlerCreateKeyJSON
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!HandlerCreateKeyJSON.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in HandlerCreateKeyJSON is not found in the empty JSON string", HandlerCreateKeyJSON.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!HandlerCreateKeyJSON.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `HandlerCreateKeyJSON` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : HandlerCreateKeyJSON.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("alias").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `alias` to be a primitive type in the JSON string but got `%s`", jsonObj.get("alias").toString()));
      }
      if (!jsonObj.get("billing_mode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `billing_mode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("billing_mode").toString()));
      }
      if ((jsonObj.get("expire_at") != null && !jsonObj.get("expire_at").isJsonNull()) && !jsonObj.get("expire_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `expire_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("expire_at").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!HandlerCreateKeyJSON.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'HandlerCreateKeyJSON' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<HandlerCreateKeyJSON> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(HandlerCreateKeyJSON.class));

       return (TypeAdapter<T>) new TypeAdapter<HandlerCreateKeyJSON>() {
           @Override
           public void write(JsonWriter out, HandlerCreateKeyJSON value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public HandlerCreateKeyJSON read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of HandlerCreateKeyJSON given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of HandlerCreateKeyJSON
   * @throws IOException if the JSON string is invalid with respect to HandlerCreateKeyJSON
   */
  public static HandlerCreateKeyJSON fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, HandlerCreateKeyJSON.class);
  }

  /**
   * Convert an instance of HandlerCreateKeyJSON to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

