/*
 * CloudKey API
 * 卡密管理系统 API 文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.ezzzi_y.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.github.ezzzi_y.JSON;

/**
 * HandlerVerify2FARequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-20T19:01:01.615859700+08:00[Asia/Shanghai]", comments = "Generator version: 7.24.0")
public class HandlerVerify2FARequest {
  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  @javax.annotation.Nonnull
  private String code;

  public static final String SERIALIZED_NAME_PRE_AUTH_TOKEN = "pre_auth_token";
  @SerializedName(SERIALIZED_NAME_PRE_AUTH_TOKEN)
  @javax.annotation.Nonnull
  private String preAuthToken;

  public static final String SERIALIZED_NAME_USER_ID = "user_id";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  @javax.annotation.Nonnull
  private Integer userId;

  public HandlerVerify2FARequest() {
  }

  public HandlerVerify2FARequest code(@javax.annotation.Nonnull String code) {
    this.code = code;
    return this;
  }

  /**
   * Get code
   * @return code
   */
  @javax.annotation.Nonnull
  public String getCode() {
    return code;
  }

  public void setCode(@javax.annotation.Nonnull String code) {
    this.code = code;
  }


  public HandlerVerify2FARequest preAuthToken(@javax.annotation.Nonnull String preAuthToken) {
    this.preAuthToken = preAuthToken;
    return this;
  }

  /**
   * Get preAuthToken
   * @return preAuthToken
   */
  @javax.annotation.Nonnull
  public String getPreAuthToken() {
    return preAuthToken;
  }

  public void setPreAuthToken(@javax.annotation.Nonnull String preAuthToken) {
    this.preAuthToken = preAuthToken;
  }


  public HandlerVerify2FARequest userId(@javax.annotation.Nonnull Integer userId) {
    this.userId = userId;
    return this;
  }

  /**
   * Get userId
   * @return userId
   */
  @javax.annotation.Nonnull
  public Integer getUserId() {
    return userId;
  }

  public void setUserId(@javax.annotation.Nonnull Integer userId) {
    this.userId = userId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HandlerVerify2FARequest handlerVerify2FARequest = (HandlerVerify2FARequest) o;
    return Objects.equals(this.code, handlerVerify2FARequest.code) &&
        Objects.equals(this.preAuthToken, handlerVerify2FARequest.preAuthToken) &&
        Objects.equals(this.userId, handlerVerify2FARequest.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, preAuthToken, userId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HandlerVerify2FARequest {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    preAuthToken: ").append(toIndentedString(preAuthToken)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("code", "pre_auth_token", "user_id"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("code", "pre_auth_token", "user_id"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to HandlerVerify2FARequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!HandlerVerify2FARequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in HandlerVerify2FARequest is not found in the empty JSON string", HandlerVerify2FARequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!HandlerVerify2FARequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `HandlerVerify2FARequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : HandlerVerify2FARequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("code").toString()));
      }
      if (!jsonObj.get("pre_auth_token").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `pre_auth_token` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pre_auth_token").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!HandlerVerify2FARequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'HandlerVerify2FARequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<HandlerVerify2FARequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(HandlerVerify2FARequest.class));

       return (TypeAdapter<T>) new TypeAdapter<HandlerVerify2FARequest>() {
           @Override
           public void write(JsonWriter out, HandlerVerify2FARequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public HandlerVerify2FARequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of HandlerVerify2FARequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of HandlerVerify2FARequest
   * @throws IOException if the JSON string is invalid with respect to HandlerVerify2FARequest
   */
  public static HandlerVerify2FARequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, HandlerVerify2FARequest.class);
  }

  /**
   * Convert an instance of HandlerVerify2FARequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

