/*
 * CloudKey Service Account API
 * 卡密管理系统 - 服务账号 SDK
 *
 * The version of the OpenAPI document: 1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.ezzzi_y.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.github.ezzzi_y.CloudKeyJSON;

/**
 * Key
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-21T15:39:59.098139500+08:00[Asia/Shanghai]", comments = "Generator version: 7.24.0")
public class Key {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Long id;

  public static final String SERIALIZED_NAME_TENANT_ID = "tenant_id";
  @SerializedName(SERIALIZED_NAME_TENANT_ID)
  @javax.annotation.Nullable
  private Long tenantId;

  public static final String SERIALIZED_NAME_ALIAS = "alias";
  @SerializedName(SERIALIZED_NAME_ALIAS)
  @javax.annotation.Nullable
  private String alias;

  public static final String SERIALIZED_NAME_KEY_PREFIX = "key_prefix";
  @SerializedName(SERIALIZED_NAME_KEY_PREFIX)
  @javax.annotation.Nullable
  private String keyPrefix;

  public static final String SERIALIZED_NAME_KEY_SUFFIX = "key_suffix";
  @SerializedName(SERIALIZED_NAME_KEY_SUFFIX)
  @javax.annotation.Nullable
  private String keySuffix;

  /**
   * Gets or Sets billingMode
   */
  @JsonAdapter(BillingModeEnum.Adapter.class)
  public enum BillingModeEnum {
    COUNT("count"),
    
    CREDIT("credit");

    private String value;

    BillingModeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static BillingModeEnum fromValue(String value) {
      for (BillingModeEnum b : BillingModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<BillingModeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final BillingModeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public BillingModeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return BillingModeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      BillingModeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_BILLING_MODE = "billing_mode";
  @SerializedName(SERIALIZED_NAME_BILLING_MODE)
  @javax.annotation.Nullable
  private BillingModeEnum billingMode;

  public static final String SERIALIZED_NAME_INITIAL_AMOUNT = "initial_amount";
  @SerializedName(SERIALIZED_NAME_INITIAL_AMOUNT)
  @javax.annotation.Nullable
  private Long initialAmount;

  public static final String SERIALIZED_NAME_REMAINING_AMOUNT = "remaining_amount";
  @SerializedName(SERIALIZED_NAME_REMAINING_AMOUNT)
  @javax.annotation.Nullable
  private Long remainingAmount;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    UNUSED("unused"),
    
    USED("used"),
    
    DISABLED("disabled"),
    
    EXPIRED("expired");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private StatusEnum status;

  public static final String SERIALIZED_NAME_CREATED_BY = "created_by";
  @SerializedName(SERIALIZED_NAME_CREATED_BY)
  @javax.annotation.Nullable
  private String createdBy;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_USED_AT = "used_at";
  @SerializedName(SERIALIZED_NAME_USED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime usedAt;

  public static final String SERIALIZED_NAME_EXPIRE_AT = "expire_at";
  @SerializedName(SERIALIZED_NAME_EXPIRE_AT)
  @javax.annotation.Nullable
  private OffsetDateTime expireAt;

  public static final String SERIALIZED_NAME_MAX_USAGE = "max_usage";
  @SerializedName(SERIALIZED_NAME_MAX_USAGE)
  @javax.annotation.Nullable
  private Long maxUsage;

  public Key() {
  }

  public Key id(@javax.annotation.Nullable Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public Long getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Long id) {
    this.id = id;
  }


  public Key tenantId(@javax.annotation.Nullable Long tenantId) {
    this.tenantId = tenantId;
    return this;
  }

  /**
   * Get tenantId
   * @return tenantId
   */
  @javax.annotation.Nullable
  public Long getTenantId() {
    return tenantId;
  }

  public void setTenantId(@javax.annotation.Nullable Long tenantId) {
    this.tenantId = tenantId;
  }


  public Key alias(@javax.annotation.Nullable String alias) {
    this.alias = alias;
    return this;
  }

  /**
   * Get alias
   * @return alias
   */
  @javax.annotation.Nullable
  public String getAlias() {
    return alias;
  }

  public void setAlias(@javax.annotation.Nullable String alias) {
    this.alias = alias;
  }


  public Key keyPrefix(@javax.annotation.Nullable String keyPrefix) {
    this.keyPrefix = keyPrefix;
    return this;
  }

  /**
   * Get keyPrefix
   * @return keyPrefix
   */
  @javax.annotation.Nullable
  public String getKeyPrefix() {
    return keyPrefix;
  }

  public void setKeyPrefix(@javax.annotation.Nullable String keyPrefix) {
    this.keyPrefix = keyPrefix;
  }


  public Key keySuffix(@javax.annotation.Nullable String keySuffix) {
    this.keySuffix = keySuffix;
    return this;
  }

  /**
   * Get keySuffix
   * @return keySuffix
   */
  @javax.annotation.Nullable
  public String getKeySuffix() {
    return keySuffix;
  }

  public void setKeySuffix(@javax.annotation.Nullable String keySuffix) {
    this.keySuffix = keySuffix;
  }


  public Key billingMode(@javax.annotation.Nullable BillingModeEnum billingMode) {
    this.billingMode = billingMode;
    return this;
  }

  /**
   * Get billingMode
   * @return billingMode
   */
  @javax.annotation.Nullable
  public BillingModeEnum getBillingMode() {
    return billingMode;
  }

  public void setBillingMode(@javax.annotation.Nullable BillingModeEnum billingMode) {
    this.billingMode = billingMode;
  }


  public Key initialAmount(@javax.annotation.Nullable Long initialAmount) {
    this.initialAmount = initialAmount;
    return this;
  }

  /**
   * Get initialAmount
   * @return initialAmount
   */
  @javax.annotation.Nullable
  public Long getInitialAmount() {
    return initialAmount;
  }

  public void setInitialAmount(@javax.annotation.Nullable Long initialAmount) {
    this.initialAmount = initialAmount;
  }


  public Key remainingAmount(@javax.annotation.Nullable Long remainingAmount) {
    this.remainingAmount = remainingAmount;
    return this;
  }

  /**
   * Get remainingAmount
   * @return remainingAmount
   */
  @javax.annotation.Nullable
  public Long getRemainingAmount() {
    return remainingAmount;
  }

  public void setRemainingAmount(@javax.annotation.Nullable Long remainingAmount) {
    this.remainingAmount = remainingAmount;
  }


  public Key status(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public Key createdBy(@javax.annotation.Nullable String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

  /**
   * Get createdBy
   * @return createdBy
   */
  @javax.annotation.Nullable
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(@javax.annotation.Nullable String createdBy) {
    this.createdBy = createdBy;
  }


  public Key createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public Key updatedAt(@javax.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public Key usedAt(@javax.annotation.Nullable OffsetDateTime usedAt) {
    this.usedAt = usedAt;
    return this;
  }

  /**
   * Get usedAt
   * @return usedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getUsedAt() {
    return usedAt;
  }

  public void setUsedAt(@javax.annotation.Nullable OffsetDateTime usedAt) {
    this.usedAt = usedAt;
  }


  public Key expireAt(@javax.annotation.Nullable OffsetDateTime expireAt) {
    this.expireAt = expireAt;
    return this;
  }

  /**
   * Get expireAt
   * @return expireAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getExpireAt() {
    return expireAt;
  }

  public void setExpireAt(@javax.annotation.Nullable OffsetDateTime expireAt) {
    this.expireAt = expireAt;
  }


  public Key maxUsage(@javax.annotation.Nullable Long maxUsage) {
    this.maxUsage = maxUsage;
    return this;
  }

  /**
   * Get maxUsage
   * @return maxUsage
   */
  @javax.annotation.Nullable
  public Long getMaxUsage() {
    return maxUsage;
  }

  public void setMaxUsage(@javax.annotation.Nullable Long maxUsage) {
    this.maxUsage = maxUsage;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Key key = (Key) o;
    return Objects.equals(this.id, key.id) &&
        Objects.equals(this.tenantId, key.tenantId) &&
        Objects.equals(this.alias, key.alias) &&
        Objects.equals(this.keyPrefix, key.keyPrefix) &&
        Objects.equals(this.keySuffix, key.keySuffix) &&
        Objects.equals(this.billingMode, key.billingMode) &&
        Objects.equals(this.initialAmount, key.initialAmount) &&
        Objects.equals(this.remainingAmount, key.remainingAmount) &&
        Objects.equals(this.status, key.status) &&
        Objects.equals(this.createdBy, key.createdBy) &&
        Objects.equals(this.createdAt, key.createdAt) &&
        Objects.equals(this.updatedAt, key.updatedAt) &&
        Objects.equals(this.usedAt, key.usedAt) &&
        Objects.equals(this.expireAt, key.expireAt) &&
        Objects.equals(this.maxUsage, key.maxUsage);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, tenantId, alias, keyPrefix, keySuffix, billingMode, initialAmount, remainingAmount, status, createdBy, createdAt, updatedAt, usedAt, expireAt, maxUsage);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Key {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("    keyPrefix: ").append(toIndentedString(keyPrefix)).append("\n");
    sb.append("    keySuffix: ").append(toIndentedString(keySuffix)).append("\n");
    sb.append("    billingMode: ").append(toIndentedString(billingMode)).append("\n");
    sb.append("    initialAmount: ").append(toIndentedString(initialAmount)).append("\n");
    sb.append("    remainingAmount: ").append(toIndentedString(remainingAmount)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    usedAt: ").append(toIndentedString(usedAt)).append("\n");
    sb.append("    expireAt: ").append(toIndentedString(expireAt)).append("\n");
    sb.append("    maxUsage: ").append(toIndentedString(maxUsage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "tenant_id", "alias", "key_prefix", "key_suffix", "billing_mode", "initial_amount", "remaining_amount", "status", "created_by", "created_at", "updated_at", "used_at", "expire_at", "max_usage"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Key
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Key.openapiRequiredFields.isEmpty()) { // has required fields but CloudKeyJSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Key is not found in the empty JSON string", Key.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Key.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Key` properties. CloudKeyJSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("alias") != null && !jsonObj.get("alias").isJsonNull()) && !jsonObj.get("alias").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `alias` to be a primitive type in the JSON string but got `%s`", jsonObj.get("alias").toString()));
      }
      if ((jsonObj.get("key_prefix") != null && !jsonObj.get("key_prefix").isJsonNull()) && !jsonObj.get("key_prefix").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `key_prefix` to be a primitive type in the JSON string but got `%s`", jsonObj.get("key_prefix").toString()));
      }
      if ((jsonObj.get("key_suffix") != null && !jsonObj.get("key_suffix").isJsonNull()) && !jsonObj.get("key_suffix").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `key_suffix` to be a primitive type in the JSON string but got `%s`", jsonObj.get("key_suffix").toString()));
      }
      if ((jsonObj.get("billing_mode") != null && !jsonObj.get("billing_mode").isJsonNull()) && !jsonObj.get("billing_mode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `billing_mode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("billing_mode").toString()));
      }
      // validate the optional field `billing_mode`
      if (jsonObj.get("billing_mode") != null && !jsonObj.get("billing_mode").isJsonNull()) {
        BillingModeEnum.validateJsonElement(jsonObj.get("billing_mode"));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        StatusEnum.validateJsonElement(jsonObj.get("status"));
      }
      if ((jsonObj.get("created_by") != null && !jsonObj.get("created_by").isJsonNull()) && !jsonObj.get("created_by").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `created_by` to be a primitive type in the JSON string but got `%s`", jsonObj.get("created_by").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Key.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Key' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Key> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Key.class));

       return (TypeAdapter<T>) new TypeAdapter<Key>() {
           @Override
           public void write(JsonWriter out, Key value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Key read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Key given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Key
   * @throws IOException if the JSON string is invalid with respect to Key
   */
  public static Key fromJson(String jsonString) throws IOException {
    return CloudKeyJSON.getGson().fromJson(jsonString, Key.class);
  }

  /**
   * Convert an instance of Key to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return CloudKeyJSON.getGson().toJson(this);
  }
}

