/*
 * CloudKey API
 * 卡密管理系统 API 文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.ezzzi_y.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.github.ezzzi_y.JSON;

/**
 * SuperTenantsIdResetPasswordPatch200ResponseAllOfData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-20T19:01:01.615859700+08:00[Asia/Shanghai]", comments = "Generator version: 7.24.0")
public class SuperTenantsIdResetPasswordPatch200ResponseAllOfData {
  public static final String SERIALIZED_NAME_NEW_PASSWORD = "new_password";
  @SerializedName(SERIALIZED_NAME_NEW_PASSWORD)
  @javax.annotation.Nullable
  private String newPassword;

  public SuperTenantsIdResetPasswordPatch200ResponseAllOfData() {
  }

  public SuperTenantsIdResetPasswordPatch200ResponseAllOfData newPassword(@javax.annotation.Nullable String newPassword) {
    this.newPassword = newPassword;
    return this;
  }

  /**
   * Get newPassword
   * @return newPassword
   */
  @javax.annotation.Nullable
  public String getNewPassword() {
    return newPassword;
  }

  public void setNewPassword(@javax.annotation.Nullable String newPassword) {
    this.newPassword = newPassword;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SuperTenantsIdResetPasswordPatch200ResponseAllOfData superTenantsIdResetPasswordPatch200ResponseAllOfData = (SuperTenantsIdResetPasswordPatch200ResponseAllOfData) o;
    return Objects.equals(this.newPassword, superTenantsIdResetPasswordPatch200ResponseAllOfData.newPassword);
  }

  @Override
  public int hashCode() {
    return Objects.hash(newPassword);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SuperTenantsIdResetPasswordPatch200ResponseAllOfData {\n");
    sb.append("    newPassword: ").append(toIndentedString(newPassword)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("new_password"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SuperTenantsIdResetPasswordPatch200ResponseAllOfData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SuperTenantsIdResetPasswordPatch200ResponseAllOfData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in SuperTenantsIdResetPasswordPatch200ResponseAllOfData is not found in the empty JSON string", SuperTenantsIdResetPasswordPatch200ResponseAllOfData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SuperTenantsIdResetPasswordPatch200ResponseAllOfData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `SuperTenantsIdResetPasswordPatch200ResponseAllOfData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("new_password") != null && !jsonObj.get("new_password").isJsonNull()) && !jsonObj.get("new_password").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `new_password` to be a primitive type in the JSON string but got `%s`", jsonObj.get("new_password").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SuperTenantsIdResetPasswordPatch200ResponseAllOfData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SuperTenantsIdResetPasswordPatch200ResponseAllOfData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SuperTenantsIdResetPasswordPatch200ResponseAllOfData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SuperTenantsIdResetPasswordPatch200ResponseAllOfData.class));

       return (TypeAdapter<T>) new TypeAdapter<SuperTenantsIdResetPasswordPatch200ResponseAllOfData>() {
           @Override
           public void write(JsonWriter out, SuperTenantsIdResetPasswordPatch200ResponseAllOfData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SuperTenantsIdResetPasswordPatch200ResponseAllOfData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SuperTenantsIdResetPasswordPatch200ResponseAllOfData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SuperTenantsIdResetPasswordPatch200ResponseAllOfData
   * @throws IOException if the JSON string is invalid with respect to SuperTenantsIdResetPasswordPatch200ResponseAllOfData
   */
  public static SuperTenantsIdResetPasswordPatch200ResponseAllOfData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SuperTenantsIdResetPasswordPatch200ResponseAllOfData.class);
  }

  /**
   * Convert an instance of SuperTenantsIdResetPasswordPatch200ResponseAllOfData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

