/*
 * CloudKey API
 * 卡密管理系统 API 文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.ezzzi_y.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.github.ezzzi_y.JSON;

/**
 * SuperTenantsPost200ResponseAllOfData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-20T19:01:01.615859700+08:00[Asia/Shanghai]", comments = "Generator version: 7.24.0")
public class SuperTenantsPost200ResponseAllOfData {
  public static final String SERIALIZED_NAME_ADMIN_PASSWORD = "admin_password";
  @SerializedName(SERIALIZED_NAME_ADMIN_PASSWORD)
  @javax.annotation.Nullable
  private String adminPassword;

  public static final String SERIALIZED_NAME_ADMIN_USERNAME = "admin_username";
  @SerializedName(SERIALIZED_NAME_ADMIN_USERNAME)
  @javax.annotation.Nullable
  private String adminUsername;

  public static final String SERIALIZED_NAME_TENANT = "tenant";
  @SerializedName(SERIALIZED_NAME_TENANT)
  @javax.annotation.Nullable
  private Object tenant;

  public SuperTenantsPost200ResponseAllOfData() {
  }

  public SuperTenantsPost200ResponseAllOfData adminPassword(@javax.annotation.Nullable String adminPassword) {
    this.adminPassword = adminPassword;
    return this;
  }

  /**
   * Get adminPassword
   * @return adminPassword
   */
  @javax.annotation.Nullable
  public String getAdminPassword() {
    return adminPassword;
  }

  public void setAdminPassword(@javax.annotation.Nullable String adminPassword) {
    this.adminPassword = adminPassword;
  }


  public SuperTenantsPost200ResponseAllOfData adminUsername(@javax.annotation.Nullable String adminUsername) {
    this.adminUsername = adminUsername;
    return this;
  }

  /**
   * Get adminUsername
   * @return adminUsername
   */
  @javax.annotation.Nullable
  public String getAdminUsername() {
    return adminUsername;
  }

  public void setAdminUsername(@javax.annotation.Nullable String adminUsername) {
    this.adminUsername = adminUsername;
  }


  public SuperTenantsPost200ResponseAllOfData tenant(@javax.annotation.Nullable Object tenant) {
    this.tenant = tenant;
    return this;
  }

  /**
   * Get tenant
   * @return tenant
   */
  @javax.annotation.Nullable
  public Object getTenant() {
    return tenant;
  }

  public void setTenant(@javax.annotation.Nullable Object tenant) {
    this.tenant = tenant;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SuperTenantsPost200ResponseAllOfData superTenantsPost200ResponseAllOfData = (SuperTenantsPost200ResponseAllOfData) o;
    return Objects.equals(this.adminPassword, superTenantsPost200ResponseAllOfData.adminPassword) &&
        Objects.equals(this.adminUsername, superTenantsPost200ResponseAllOfData.adminUsername) &&
        Objects.equals(this.tenant, superTenantsPost200ResponseAllOfData.tenant);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adminPassword, adminUsername, tenant);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SuperTenantsPost200ResponseAllOfData {\n");
    sb.append("    adminPassword: ").append(toIndentedString(adminPassword)).append("\n");
    sb.append("    adminUsername: ").append(toIndentedString(adminUsername)).append("\n");
    sb.append("    tenant: ").append(toIndentedString(tenant)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("admin_password", "admin_username", "tenant"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SuperTenantsPost200ResponseAllOfData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SuperTenantsPost200ResponseAllOfData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in SuperTenantsPost200ResponseAllOfData is not found in the empty JSON string", SuperTenantsPost200ResponseAllOfData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SuperTenantsPost200ResponseAllOfData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `SuperTenantsPost200ResponseAllOfData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("admin_password") != null && !jsonObj.get("admin_password").isJsonNull()) && !jsonObj.get("admin_password").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `admin_password` to be a primitive type in the JSON string but got `%s`", jsonObj.get("admin_password").toString()));
      }
      if ((jsonObj.get("admin_username") != null && !jsonObj.get("admin_username").isJsonNull()) && !jsonObj.get("admin_username").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `admin_username` to be a primitive type in the JSON string but got `%s`", jsonObj.get("admin_username").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SuperTenantsPost200ResponseAllOfData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SuperTenantsPost200ResponseAllOfData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SuperTenantsPost200ResponseAllOfData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SuperTenantsPost200ResponseAllOfData.class));

       return (TypeAdapter<T>) new TypeAdapter<SuperTenantsPost200ResponseAllOfData>() {
           @Override
           public void write(JsonWriter out, SuperTenantsPost200ResponseAllOfData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SuperTenantsPost200ResponseAllOfData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SuperTenantsPost200ResponseAllOfData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SuperTenantsPost200ResponseAllOfData
   * @throws IOException if the JSON string is invalid with respect to SuperTenantsPost200ResponseAllOfData
   */
  public static SuperTenantsPost200ResponseAllOfData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SuperTenantsPost200ResponseAllOfData.class);
  }

  /**
   * Convert an instance of SuperTenantsPost200ResponseAllOfData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

