/*
 * CloudKey Service Account API
 * 卡密管理系统 - 服务账号 SDK
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.ezzzi_y.api;

import com.github.ezzzi_y.ApiCallback;
import com.github.ezzzi_y.ApiClient;
import com.github.ezzzi_y.ApiException;
import com.github.ezzzi_y.ApiResponse;
import com.github.ezzzi_y.Configuration;
import com.github.ezzzi_y.Pair;
import com.github.ezzzi_y.ProgressRequestBody;
import com.github.ezzzi_y.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.github.ezzzi_y.model.HandlerResponse;
import com.github.ezzzi_y.model.HandlerServiceConsumeReq;
import com.github.ezzzi_y.model.ServiceKeysGet200Response;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ApiApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ApiApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ApiApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for serviceKeysConsumePost
     * @param body 扣减参数 (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 扣减结果 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 参数错误或卡密无效 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call serviceKeysConsumePostCall(@javax.annotation.Nonnull HandlerServiceConsumeReq body, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/service/keys/consume";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ServiceKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call serviceKeysConsumePostValidateBeforeCall(@javax.annotation.Nonnull HandlerServiceConsumeReq body, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'body' is set
        if (body == null) {
            throw new ApiException("Missing the required parameter 'body' when calling serviceKeysConsumePost(Async)");
        }

        return serviceKeysConsumePostCall(body, _callback);

    }

    /**
     * 服务账号扣减卡密额度
     * 通过 X-Service-Key 认证，扣减指定卡密的剩余额度
     * @param body 扣减参数 (required)
     * @return HandlerResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 扣减结果 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 参数错误或卡密无效 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public HandlerResponse serviceKeysConsumePost(@javax.annotation.Nonnull HandlerServiceConsumeReq body) throws ApiException {
        ApiResponse<HandlerResponse> localVarResp = serviceKeysConsumePostWithHttpInfo(body);
        return localVarResp.getData();
    }

    /**
     * 服务账号扣减卡密额度
     * 通过 X-Service-Key 认证，扣减指定卡密的剩余额度
     * @param body 扣减参数 (required)
     * @return ApiResponse&lt;HandlerResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 扣减结果 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 参数错误或卡密无效 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<HandlerResponse> serviceKeysConsumePostWithHttpInfo(@javax.annotation.Nonnull HandlerServiceConsumeReq body) throws ApiException {
        okhttp3.Call localVarCall = serviceKeysConsumePostValidateBeforeCall(body, null);
        Type localVarReturnType = new TypeToken<HandlerResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 服务账号扣减卡密额度 (asynchronously)
     * 通过 X-Service-Key 认证，扣减指定卡密的剩余额度
     * @param body 扣减参数 (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 扣减结果 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 参数错误或卡密无效 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call serviceKeysConsumePostAsync(@javax.annotation.Nonnull HandlerServiceConsumeReq body, final ApiCallback<HandlerResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = serviceKeysConsumePostValidateBeforeCall(body, _callback);
        Type localVarReturnType = new TypeToken<HandlerResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for serviceKeysExportGet
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 导出数据 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call serviceKeysExportGetCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/service/keys/export";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ServiceKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call serviceKeysExportGetValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return serviceKeysExportGetCall(_callback);

    }

    /**
     * 服务账号导出卡密（文本格式）
     * 
     * @return HandlerResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 导出数据 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public HandlerResponse serviceKeysExportGet() throws ApiException {
        ApiResponse<HandlerResponse> localVarResp = serviceKeysExportGetWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * 服务账号导出卡密（文本格式）
     * 
     * @return ApiResponse&lt;HandlerResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 导出数据 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<HandlerResponse> serviceKeysExportGetWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = serviceKeysExportGetValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<HandlerResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 服务账号导出卡密（文本格式） (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 导出数据 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call serviceKeysExportGetAsync(final ApiCallback<HandlerResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = serviceKeysExportGetValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<HandlerResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for serviceKeysExportJsonGet
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 导出数据 JSON 数组 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call serviceKeysExportJsonGetCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/service/keys/export/json";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ServiceKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call serviceKeysExportJsonGetValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return serviceKeysExportJsonGetCall(_callback);

    }

    /**
     * 服务账号导出卡密（JSON 格式）
     * 
     * @return HandlerResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 导出数据 JSON 数组 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public HandlerResponse serviceKeysExportJsonGet() throws ApiException {
        ApiResponse<HandlerResponse> localVarResp = serviceKeysExportJsonGetWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * 服务账号导出卡密（JSON 格式）
     * 
     * @return ApiResponse&lt;HandlerResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 导出数据 JSON 数组 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<HandlerResponse> serviceKeysExportJsonGetWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = serviceKeysExportJsonGetValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<HandlerResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 服务账号导出卡密（JSON 格式） (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 导出数据 JSON 数组 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call serviceKeysExportJsonGetAsync(final ApiCallback<HandlerResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = serviceKeysExportJsonGetValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<HandlerResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for serviceKeysGet
     * @param page 页码 (optional, default to 1)
     * @param pageSize 每页数量 (optional, default to 20)
     * @param status 状态过滤: unused/used/disabled/expired (optional)
     * @param search 关键字搜索 (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 分页卡密列表 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call serviceKeysGetCall(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer pageSize, @javax.annotation.Nullable String status, @javax.annotation.Nullable String search, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/service/keys";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (pageSize != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page_size", pageSize));
        }

        if (status != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("status", status));
        }

        if (search != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("search", search));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ServiceKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call serviceKeysGetValidateBeforeCall(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer pageSize, @javax.annotation.Nullable String status, @javax.annotation.Nullable String search, final ApiCallback _callback) throws ApiException {
        return serviceKeysGetCall(page, pageSize, status, search, _callback);

    }

    /**
     * 服务账号查询卡密列表
     * 
     * @param page 页码 (optional, default to 1)
     * @param pageSize 每页数量 (optional, default to 20)
     * @param status 状态过滤: unused/used/disabled/expired (optional)
     * @param search 关键字搜索 (optional)
     * @return ServiceKeysGet200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 分页卡密列表 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public ServiceKeysGet200Response serviceKeysGet(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer pageSize, @javax.annotation.Nullable String status, @javax.annotation.Nullable String search) throws ApiException {
        ApiResponse<ServiceKeysGet200Response> localVarResp = serviceKeysGetWithHttpInfo(page, pageSize, status, search);
        return localVarResp.getData();
    }

    /**
     * 服务账号查询卡密列表
     * 
     * @param page 页码 (optional, default to 1)
     * @param pageSize 每页数量 (optional, default to 20)
     * @param status 状态过滤: unused/used/disabled/expired (optional)
     * @param search 关键字搜索 (optional)
     * @return ApiResponse&lt;ServiceKeysGet200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 分页卡密列表 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ServiceKeysGet200Response> serviceKeysGetWithHttpInfo(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer pageSize, @javax.annotation.Nullable String status, @javax.annotation.Nullable String search) throws ApiException {
        okhttp3.Call localVarCall = serviceKeysGetValidateBeforeCall(page, pageSize, status, search, null);
        Type localVarReturnType = new TypeToken<ServiceKeysGet200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 服务账号查询卡密列表 (asynchronously)
     * 
     * @param page 页码 (optional, default to 1)
     * @param pageSize 每页数量 (optional, default to 20)
     * @param status 状态过滤: unused/used/disabled/expired (optional)
     * @param search 关键字搜索 (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 分页卡密列表 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call serviceKeysGetAsync(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer pageSize, @javax.annotation.Nullable String status, @javax.annotation.Nullable String search, final ApiCallback<ServiceKeysGet200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = serviceKeysGetValidateBeforeCall(page, pageSize, status, search, _callback);
        Type localVarReturnType = new TypeToken<ServiceKeysGet200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for serviceKeysIdDelete
     * @param id 卡密ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 删除成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call serviceKeysIdDeleteCall(@javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/service/keys/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ServiceKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call serviceKeysIdDeleteValidateBeforeCall(@javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling serviceKeysIdDelete(Async)");
        }

        return serviceKeysIdDeleteCall(id, _callback);

    }

    /**
     * 服务账号删除卡密
     * 
     * @param id 卡密ID (required)
     * @return HandlerResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 删除成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public HandlerResponse serviceKeysIdDelete(@javax.annotation.Nonnull Integer id) throws ApiException {
        ApiResponse<HandlerResponse> localVarResp = serviceKeysIdDeleteWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * 服务账号删除卡密
     * 
     * @param id 卡密ID (required)
     * @return ApiResponse&lt;HandlerResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 删除成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<HandlerResponse> serviceKeysIdDeleteWithHttpInfo(@javax.annotation.Nonnull Integer id) throws ApiException {
        okhttp3.Call localVarCall = serviceKeysIdDeleteValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<HandlerResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 服务账号删除卡密 (asynchronously)
     * 
     * @param id 卡密ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 删除成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call serviceKeysIdDeleteAsync(@javax.annotation.Nonnull Integer id, final ApiCallback<HandlerResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = serviceKeysIdDeleteValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<HandlerResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for serviceKeysIdDisablePatch
     * @param id 卡密ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 禁用成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call serviceKeysIdDisablePatchCall(@javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/service/keys/{id}/disable"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ServiceKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call serviceKeysIdDisablePatchValidateBeforeCall(@javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling serviceKeysIdDisablePatch(Async)");
        }

        return serviceKeysIdDisablePatchCall(id, _callback);

    }

    /**
     * 服务账号禁用卡密
     * 
     * @param id 卡密ID (required)
     * @return HandlerResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 禁用成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public HandlerResponse serviceKeysIdDisablePatch(@javax.annotation.Nonnull Integer id) throws ApiException {
        ApiResponse<HandlerResponse> localVarResp = serviceKeysIdDisablePatchWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * 服务账号禁用卡密
     * 
     * @param id 卡密ID (required)
     * @return ApiResponse&lt;HandlerResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 禁用成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<HandlerResponse> serviceKeysIdDisablePatchWithHttpInfo(@javax.annotation.Nonnull Integer id) throws ApiException {
        okhttp3.Call localVarCall = serviceKeysIdDisablePatchValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<HandlerResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 服务账号禁用卡密 (asynchronously)
     * 
     * @param id 卡密ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 禁用成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call serviceKeysIdDisablePatchAsync(@javax.annotation.Nonnull Integer id, final ApiCallback<HandlerResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = serviceKeysIdDisablePatchValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<HandlerResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for serviceKeysIdEnablePatch
     * @param id 卡密ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 启用成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call serviceKeysIdEnablePatchCall(@javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/service/keys/{id}/enable"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ServiceKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call serviceKeysIdEnablePatchValidateBeforeCall(@javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling serviceKeysIdEnablePatch(Async)");
        }

        return serviceKeysIdEnablePatchCall(id, _callback);

    }

    /**
     * 服务账号启用卡密
     * 
     * @param id 卡密ID (required)
     * @return HandlerResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 启用成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public HandlerResponse serviceKeysIdEnablePatch(@javax.annotation.Nonnull Integer id) throws ApiException {
        ApiResponse<HandlerResponse> localVarResp = serviceKeysIdEnablePatchWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * 服务账号启用卡密
     * 
     * @param id 卡密ID (required)
     * @return ApiResponse&lt;HandlerResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 启用成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<HandlerResponse> serviceKeysIdEnablePatchWithHttpInfo(@javax.annotation.Nonnull Integer id) throws ApiException {
        okhttp3.Call localVarCall = serviceKeysIdEnablePatchValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<HandlerResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 服务账号启用卡密 (asynchronously)
     * 
     * @param id 卡密ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 启用成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call serviceKeysIdEnablePatchAsync(@javax.annotation.Nonnull Integer id, final ApiCallback<HandlerResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = serviceKeysIdEnablePatchValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<HandlerResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for serviceKeysIdGet
     * @param id 卡密ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 卡密详情 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 卡密不存在 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call serviceKeysIdGetCall(@javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/service/keys/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ServiceKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call serviceKeysIdGetValidateBeforeCall(@javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling serviceKeysIdGet(Async)");
        }

        return serviceKeysIdGetCall(id, _callback);

    }

    /**
     * 服务账号查询卡密详情
     * 
     * @param id 卡密ID (required)
     * @return HandlerResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 卡密详情 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 卡密不存在 </td><td>  -  </td></tr>
     </table>
     */
    public HandlerResponse serviceKeysIdGet(@javax.annotation.Nonnull Integer id) throws ApiException {
        ApiResponse<HandlerResponse> localVarResp = serviceKeysIdGetWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * 服务账号查询卡密详情
     * 
     * @param id 卡密ID (required)
     * @return ApiResponse&lt;HandlerResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 卡密详情 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 卡密不存在 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<HandlerResponse> serviceKeysIdGetWithHttpInfo(@javax.annotation.Nonnull Integer id) throws ApiException {
        okhttp3.Call localVarCall = serviceKeysIdGetValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<HandlerResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 服务账号查询卡密详情 (asynchronously)
     * 
     * @param id 卡密ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 卡密详情 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 卡密不存在 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call serviceKeysIdGetAsync(@javax.annotation.Nonnull Integer id, final ApiCallback<HandlerResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = serviceKeysIdGetValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<HandlerResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for serviceKeysIdPatch
     * @param id 卡密ID (required)
     * @param body 更新字段 (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 更新成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 参数错误 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call serviceKeysIdPatchCall(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull Object body, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/service/keys/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ServiceKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call serviceKeysIdPatchValidateBeforeCall(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull Object body, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling serviceKeysIdPatch(Async)");
        }

        // verify the required parameter 'body' is set
        if (body == null) {
            throw new ApiException("Missing the required parameter 'body' when calling serviceKeysIdPatch(Async)");
        }

        return serviceKeysIdPatchCall(id, body, _callback);

    }

    /**
     * 服务账号更新卡密
     * 
     * @param id 卡密ID (required)
     * @param body 更新字段 (required)
     * @return HandlerResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 更新成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 参数错误 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public HandlerResponse serviceKeysIdPatch(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull Object body) throws ApiException {
        ApiResponse<HandlerResponse> localVarResp = serviceKeysIdPatchWithHttpInfo(id, body);
        return localVarResp.getData();
    }

    /**
     * 服务账号更新卡密
     * 
     * @param id 卡密ID (required)
     * @param body 更新字段 (required)
     * @return ApiResponse&lt;HandlerResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 更新成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 参数错误 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<HandlerResponse> serviceKeysIdPatchWithHttpInfo(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull Object body) throws ApiException {
        okhttp3.Call localVarCall = serviceKeysIdPatchValidateBeforeCall(id, body, null);
        Type localVarReturnType = new TypeToken<HandlerResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 服务账号更新卡密 (asynchronously)
     * 
     * @param id 卡密ID (required)
     * @param body 更新字段 (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 更新成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 参数错误 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call serviceKeysIdPatchAsync(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull Object body, final ApiCallback<HandlerResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = serviceKeysIdPatchValidateBeforeCall(id, body, _callback);
        Type localVarReturnType = new TypeToken<HandlerResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for serviceKeysPost
     * @param body 卡密参数 (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 创建成功 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call serviceKeysPostCall(@javax.annotation.Nonnull Object body, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/service/keys";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ServiceKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call serviceKeysPostValidateBeforeCall(@javax.annotation.Nonnull Object body, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'body' is set
        if (body == null) {
            throw new ApiException("Missing the required parameter 'body' when calling serviceKeysPost(Async)");
        }

        return serviceKeysPostCall(body, _callback);

    }

    /**
     * 服务账号创建卡密
     * 通过 X-Service-Key 认证，服务账号创建卡密
     * @param body 卡密参数 (required)
     * @return HandlerResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 创建成功 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public HandlerResponse serviceKeysPost(@javax.annotation.Nonnull Object body) throws ApiException {
        ApiResponse<HandlerResponse> localVarResp = serviceKeysPostWithHttpInfo(body);
        return localVarResp.getData();
    }

    /**
     * 服务账号创建卡密
     * 通过 X-Service-Key 认证，服务账号创建卡密
     * @param body 卡密参数 (required)
     * @return ApiResponse&lt;HandlerResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 创建成功 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<HandlerResponse> serviceKeysPostWithHttpInfo(@javax.annotation.Nonnull Object body) throws ApiException {
        okhttp3.Call localVarCall = serviceKeysPostValidateBeforeCall(body, null);
        Type localVarReturnType = new TypeToken<HandlerResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 服务账号创建卡密 (asynchronously)
     * 通过 X-Service-Key 认证，服务账号创建卡密
     * @param body 卡密参数 (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 创建成功 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call serviceKeysPostAsync(@javax.annotation.Nonnull Object body, final ApiCallback<HandlerResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = serviceKeysPostValidateBeforeCall(body, _callback);
        Type localVarReturnType = new TypeToken<HandlerResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for serviceKeysStatusGet
     * @param sk 卡密值 (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 卡密状态信息 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 缺少卡密参数 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 卡密不存在 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call serviceKeysStatusGetCall(@javax.annotation.Nonnull String sk, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/service/keys/status";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (sk != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sk", sk));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ServiceKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call serviceKeysStatusGetValidateBeforeCall(@javax.annotation.Nonnull String sk, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'sk' is set
        if (sk == null) {
            throw new ApiException("Missing the required parameter 'sk' when calling serviceKeysStatusGet(Async)");
        }

        return serviceKeysStatusGetCall(sk, _callback);

    }

    /**
     * 服务账号查询卡密状态
     * 通过 X-Service-Key 认证，根据卡密值查询状态
     * @param sk 卡密值 (required)
     * @return HandlerResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 卡密状态信息 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 缺少卡密参数 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 卡密不存在 </td><td>  -  </td></tr>
     </table>
     */
    public HandlerResponse serviceKeysStatusGet(@javax.annotation.Nonnull String sk) throws ApiException {
        ApiResponse<HandlerResponse> localVarResp = serviceKeysStatusGetWithHttpInfo(sk);
        return localVarResp.getData();
    }

    /**
     * 服务账号查询卡密状态
     * 通过 X-Service-Key 认证，根据卡密值查询状态
     * @param sk 卡密值 (required)
     * @return ApiResponse&lt;HandlerResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 卡密状态信息 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 缺少卡密参数 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 卡密不存在 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<HandlerResponse> serviceKeysStatusGetWithHttpInfo(@javax.annotation.Nonnull String sk) throws ApiException {
        okhttp3.Call localVarCall = serviceKeysStatusGetValidateBeforeCall(sk, null);
        Type localVarReturnType = new TypeToken<HandlerResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 服务账号查询卡密状态 (asynchronously)
     * 通过 X-Service-Key 认证，根据卡密值查询状态
     * @param sk 卡密值 (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 卡密状态信息 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 缺少卡密参数 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 卡密不存在 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call serviceKeysStatusGetAsync(@javax.annotation.Nonnull String sk, final ApiCallback<HandlerResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = serviceKeysStatusGetValidateBeforeCall(sk, _callback);
        Type localVarReturnType = new TypeToken<HandlerResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
