/*
 * CloudKey Service Account API
 * 卡密管理系统 - 服务账号 SDK
 *
 * The version of the OpenAPI document: 1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.ezzzi_y.api;

import com.github.ezzzi_y.CloudKeyCallback;
import com.github.ezzzi_y.CloudKeyClient;
import com.github.ezzzi_y.CloudKeyException;
import com.github.ezzzi_y.CloudKeyResponse;
import com.github.ezzzi_y.CloudKeyConfiguration;
import com.github.ezzzi_y.Pair;
import com.github.ezzzi_y.ProgressRequestBody;
import com.github.ezzzi_y.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.github.ezzzi_y.model.ConsumeRequest;
import com.github.ezzzi_y.model.ConsumeResponse;
import com.github.ezzzi_y.model.CreateKeyRequest;
import com.github.ezzzi_y.model.CreateKeyResponse;
import com.github.ezzzi_y.model.ExportKeysResponse;
import com.github.ezzzi_y.model.KeyListResponse;
import com.github.ezzzi_y.model.KeyResponse;
import com.github.ezzzi_y.model.KeyStatusResponse;
import com.github.ezzzi_y.model.Result;
import com.github.ezzzi_y.model.UpdateKeyRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ServiceKeysApi {
    private CloudKeyClient localVarCloudKeyClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ServiceKeysApi() {
        this(CloudKeyConfiguration.getDefaultCloudKeyClient());
    }

    public ServiceKeysApi(CloudKeyClient apiClient) {
        this.localVarCloudKeyClient = apiClient;
    }

    public CloudKeyClient getCloudKeyClient() {
        return localVarCloudKeyClient;
    }

    public void setCloudKeyClient(CloudKeyClient apiClient) {
        this.localVarCloudKeyClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for consumeKey
     * @param body 扣减参数 (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws CloudKeyException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 扣减结果 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 参数错误或卡密无效 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call consumeKeyCall(@javax.annotation.Nonnull ConsumeRequest body, final CloudKeyCallback _callback) throws CloudKeyException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/service/keys/consume";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarCloudKeyClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarCloudKeyClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ServiceKeyAuth" };
        return localVarCloudKeyClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call consumeKeyValidateBeforeCall(@javax.annotation.Nonnull ConsumeRequest body, final CloudKeyCallback _callback) throws CloudKeyException {
        // verify the required parameter 'body' is set
        if (body == null) {
            throw new CloudKeyException("Missing the required parameter 'body' when calling consumeKey(Async)");
        }

        return consumeKeyCall(body, _callback);

    }

    /**
     * 服务账号扣减卡密额度
     * 通过 X-Service-Key 认证，扣减指定卡密的剩余额度
     * @param body 扣减参数 (required)
     * @return ConsumeResponse
     * @throws CloudKeyException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 扣减结果 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 参数错误或卡密无效 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public ConsumeResponse consumeKey(@javax.annotation.Nonnull ConsumeRequest body) throws CloudKeyException {
        CloudKeyResponse<ConsumeResponse> localVarResp = consumeKeyWithHttpInfo(body);
        return localVarResp.getData();
    }

    /**
     * 服务账号扣减卡密额度
     * 通过 X-Service-Key 认证，扣减指定卡密的剩余额度
     * @param body 扣减参数 (required)
     * @return CloudKeyResponse&lt;ConsumeResponse&gt;
     * @throws CloudKeyException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 扣减结果 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 参数错误或卡密无效 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public CloudKeyResponse<ConsumeResponse> consumeKeyWithHttpInfo(@javax.annotation.Nonnull ConsumeRequest body) throws CloudKeyException {
        okhttp3.Call localVarCall = consumeKeyValidateBeforeCall(body, null);
        Type localVarReturnType = new TypeToken<ConsumeResponse>(){}.getType();
        return localVarCloudKeyClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 服务账号扣减卡密额度 (asynchronously)
     * 通过 X-Service-Key 认证，扣减指定卡密的剩余额度
     * @param body 扣减参数 (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws CloudKeyException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 扣减结果 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 参数错误或卡密无效 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call consumeKeyAsync(@javax.annotation.Nonnull ConsumeRequest body, final CloudKeyCallback<ConsumeResponse> _callback) throws CloudKeyException {

        okhttp3.Call localVarCall = consumeKeyValidateBeforeCall(body, _callback);
        Type localVarReturnType = new TypeToken<ConsumeResponse>(){}.getType();
        localVarCloudKeyClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for createKey
     * @param body 卡密参数 (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws CloudKeyException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 创建成功 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createKeyCall(@javax.annotation.Nonnull CreateKeyRequest body, final CloudKeyCallback _callback) throws CloudKeyException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/service/keys";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarCloudKeyClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarCloudKeyClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ServiceKeyAuth" };
        return localVarCloudKeyClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createKeyValidateBeforeCall(@javax.annotation.Nonnull CreateKeyRequest body, final CloudKeyCallback _callback) throws CloudKeyException {
        // verify the required parameter 'body' is set
        if (body == null) {
            throw new CloudKeyException("Missing the required parameter 'body' when calling createKey(Async)");
        }

        return createKeyCall(body, _callback);

    }

    /**
     * 服务账号创建卡密
     * 通过 X-Service-Key 认证，服务账号创建卡密
     * @param body 卡密参数 (required)
     * @return CreateKeyResponse
     * @throws CloudKeyException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 创建成功 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public CreateKeyResponse createKey(@javax.annotation.Nonnull CreateKeyRequest body) throws CloudKeyException {
        CloudKeyResponse<CreateKeyResponse> localVarResp = createKeyWithHttpInfo(body);
        return localVarResp.getData();
    }

    /**
     * 服务账号创建卡密
     * 通过 X-Service-Key 认证，服务账号创建卡密
     * @param body 卡密参数 (required)
     * @return CloudKeyResponse&lt;CreateKeyResponse&gt;
     * @throws CloudKeyException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 创建成功 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public CloudKeyResponse<CreateKeyResponse> createKeyWithHttpInfo(@javax.annotation.Nonnull CreateKeyRequest body) throws CloudKeyException {
        okhttp3.Call localVarCall = createKeyValidateBeforeCall(body, null);
        Type localVarReturnType = new TypeToken<CreateKeyResponse>(){}.getType();
        return localVarCloudKeyClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 服务账号创建卡密 (asynchronously)
     * 通过 X-Service-Key 认证，服务账号创建卡密
     * @param body 卡密参数 (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws CloudKeyException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 创建成功 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createKeyAsync(@javax.annotation.Nonnull CreateKeyRequest body, final CloudKeyCallback<CreateKeyResponse> _callback) throws CloudKeyException {

        okhttp3.Call localVarCall = createKeyValidateBeforeCall(body, _callback);
        Type localVarReturnType = new TypeToken<CreateKeyResponse>(){}.getType();
        localVarCloudKeyClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteKey
     * @param id 卡密ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws CloudKeyException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 删除成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteKeyCall(@javax.annotation.Nonnull Integer id, final CloudKeyCallback _callback) throws CloudKeyException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/service/keys/{id}"
            .replace("{" + "id" + "}", localVarCloudKeyClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarCloudKeyClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarCloudKeyClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ServiceKeyAuth" };
        return localVarCloudKeyClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteKeyValidateBeforeCall(@javax.annotation.Nonnull Integer id, final CloudKeyCallback _callback) throws CloudKeyException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new CloudKeyException("Missing the required parameter 'id' when calling deleteKey(Async)");
        }

        return deleteKeyCall(id, _callback);

    }

    /**
     * 服务账号删除卡密
     * 
     * @param id 卡密ID (required)
     * @return Result
     * @throws CloudKeyException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 删除成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public Result deleteKey(@javax.annotation.Nonnull Integer id) throws CloudKeyException {
        CloudKeyResponse<Result> localVarResp = deleteKeyWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * 服务账号删除卡密
     * 
     * @param id 卡密ID (required)
     * @return CloudKeyResponse&lt;Result&gt;
     * @throws CloudKeyException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 删除成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public CloudKeyResponse<Result> deleteKeyWithHttpInfo(@javax.annotation.Nonnull Integer id) throws CloudKeyException {
        okhttp3.Call localVarCall = deleteKeyValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<Result>(){}.getType();
        return localVarCloudKeyClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 服务账号删除卡密 (asynchronously)
     * 
     * @param id 卡密ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws CloudKeyException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 删除成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteKeyAsync(@javax.annotation.Nonnull Integer id, final CloudKeyCallback<Result> _callback) throws CloudKeyException {

        okhttp3.Call localVarCall = deleteKeyValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<Result>(){}.getType();
        localVarCloudKeyClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for disableKey
     * @param id 卡密ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws CloudKeyException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 禁用成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call disableKeyCall(@javax.annotation.Nonnull Integer id, final CloudKeyCallback _callback) throws CloudKeyException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/service/keys/{id}/disable"
            .replace("{" + "id" + "}", localVarCloudKeyClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarCloudKeyClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarCloudKeyClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ServiceKeyAuth" };
        return localVarCloudKeyClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call disableKeyValidateBeforeCall(@javax.annotation.Nonnull Integer id, final CloudKeyCallback _callback) throws CloudKeyException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new CloudKeyException("Missing the required parameter 'id' when calling disableKey(Async)");
        }

        return disableKeyCall(id, _callback);

    }

    /**
     * 服务账号禁用卡密
     * 
     * @param id 卡密ID (required)
     * @return Result
     * @throws CloudKeyException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 禁用成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public Result disableKey(@javax.annotation.Nonnull Integer id) throws CloudKeyException {
        CloudKeyResponse<Result> localVarResp = disableKeyWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * 服务账号禁用卡密
     * 
     * @param id 卡密ID (required)
     * @return CloudKeyResponse&lt;Result&gt;
     * @throws CloudKeyException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 禁用成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public CloudKeyResponse<Result> disableKeyWithHttpInfo(@javax.annotation.Nonnull Integer id) throws CloudKeyException {
        okhttp3.Call localVarCall = disableKeyValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<Result>(){}.getType();
        return localVarCloudKeyClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 服务账号禁用卡密 (asynchronously)
     * 
     * @param id 卡密ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws CloudKeyException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 禁用成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call disableKeyAsync(@javax.annotation.Nonnull Integer id, final CloudKeyCallback<Result> _callback) throws CloudKeyException {

        okhttp3.Call localVarCall = disableKeyValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<Result>(){}.getType();
        localVarCloudKeyClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for enableKey
     * @param id 卡密ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws CloudKeyException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 启用成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call enableKeyCall(@javax.annotation.Nonnull Integer id, final CloudKeyCallback _callback) throws CloudKeyException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/service/keys/{id}/enable"
            .replace("{" + "id" + "}", localVarCloudKeyClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarCloudKeyClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarCloudKeyClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ServiceKeyAuth" };
        return localVarCloudKeyClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call enableKeyValidateBeforeCall(@javax.annotation.Nonnull Integer id, final CloudKeyCallback _callback) throws CloudKeyException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new CloudKeyException("Missing the required parameter 'id' when calling enableKey(Async)");
        }

        return enableKeyCall(id, _callback);

    }

    /**
     * 服务账号启用卡密
     * 
     * @param id 卡密ID (required)
     * @return Result
     * @throws CloudKeyException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 启用成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public Result enableKey(@javax.annotation.Nonnull Integer id) throws CloudKeyException {
        CloudKeyResponse<Result> localVarResp = enableKeyWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * 服务账号启用卡密
     * 
     * @param id 卡密ID (required)
     * @return CloudKeyResponse&lt;Result&gt;
     * @throws CloudKeyException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 启用成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public CloudKeyResponse<Result> enableKeyWithHttpInfo(@javax.annotation.Nonnull Integer id) throws CloudKeyException {
        okhttp3.Call localVarCall = enableKeyValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<Result>(){}.getType();
        return localVarCloudKeyClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 服务账号启用卡密 (asynchronously)
     * 
     * @param id 卡密ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws CloudKeyException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 启用成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call enableKeyAsync(@javax.annotation.Nonnull Integer id, final CloudKeyCallback<Result> _callback) throws CloudKeyException {

        okhttp3.Call localVarCall = enableKeyValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<Result>(){}.getType();
        localVarCloudKeyClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for exportKeys
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws CloudKeyException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 导出数据（文本格式） </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call exportKeysCall(final CloudKeyCallback _callback) throws CloudKeyException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/service/keys/export";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarCloudKeyClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarCloudKeyClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ServiceKeyAuth" };
        return localVarCloudKeyClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call exportKeysValidateBeforeCall(final CloudKeyCallback _callback) throws CloudKeyException {
        return exportKeysCall(_callback);

    }

    /**
     * 服务账号导出卡密（文本格式）
     * 
     * @return Result
     * @throws CloudKeyException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 导出数据（文本格式） </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public Result exportKeys() throws CloudKeyException {
        CloudKeyResponse<Result> localVarResp = exportKeysWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * 服务账号导出卡密（文本格式）
     * 
     * @return CloudKeyResponse&lt;Result&gt;
     * @throws CloudKeyException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 导出数据（文本格式） </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public CloudKeyResponse<Result> exportKeysWithHttpInfo() throws CloudKeyException {
        okhttp3.Call localVarCall = exportKeysValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<Result>(){}.getType();
        return localVarCloudKeyClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 服务账号导出卡密（文本格式） (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws CloudKeyException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 导出数据（文本格式） </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call exportKeysAsync(final CloudKeyCallback<Result> _callback) throws CloudKeyException {

        okhttp3.Call localVarCall = exportKeysValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<Result>(){}.getType();
        localVarCloudKeyClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for exportKeysJson
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws CloudKeyException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 导出数据 JSON 数组 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call exportKeysJsonCall(final CloudKeyCallback _callback) throws CloudKeyException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/service/keys/export/json";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarCloudKeyClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarCloudKeyClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ServiceKeyAuth" };
        return localVarCloudKeyClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call exportKeysJsonValidateBeforeCall(final CloudKeyCallback _callback) throws CloudKeyException {
        return exportKeysJsonCall(_callback);

    }

    /**
     * 服务账号导出卡密（JSON 格式）
     * 
     * @return ExportKeysResponse
     * @throws CloudKeyException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 导出数据 JSON 数组 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public ExportKeysResponse exportKeysJson() throws CloudKeyException {
        CloudKeyResponse<ExportKeysResponse> localVarResp = exportKeysJsonWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * 服务账号导出卡密（JSON 格式）
     * 
     * @return CloudKeyResponse&lt;ExportKeysResponse&gt;
     * @throws CloudKeyException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 导出数据 JSON 数组 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public CloudKeyResponse<ExportKeysResponse> exportKeysJsonWithHttpInfo() throws CloudKeyException {
        okhttp3.Call localVarCall = exportKeysJsonValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<ExportKeysResponse>(){}.getType();
        return localVarCloudKeyClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 服务账号导出卡密（JSON 格式） (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws CloudKeyException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 导出数据 JSON 数组 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call exportKeysJsonAsync(final CloudKeyCallback<ExportKeysResponse> _callback) throws CloudKeyException {

        okhttp3.Call localVarCall = exportKeysJsonValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<ExportKeysResponse>(){}.getType();
        localVarCloudKeyClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getKey
     * @param id 卡密ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws CloudKeyException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 卡密详情 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 卡密不存在 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getKeyCall(@javax.annotation.Nonnull Integer id, final CloudKeyCallback _callback) throws CloudKeyException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/service/keys/{id}"
            .replace("{" + "id" + "}", localVarCloudKeyClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarCloudKeyClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarCloudKeyClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ServiceKeyAuth" };
        return localVarCloudKeyClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getKeyValidateBeforeCall(@javax.annotation.Nonnull Integer id, final CloudKeyCallback _callback) throws CloudKeyException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new CloudKeyException("Missing the required parameter 'id' when calling getKey(Async)");
        }

        return getKeyCall(id, _callback);

    }

    /**
     * 服务账号查询卡密详情
     * 
     * @param id 卡密ID (required)
     * @return KeyResponse
     * @throws CloudKeyException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 卡密详情 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 卡密不存在 </td><td>  -  </td></tr>
     </table>
     */
    public KeyResponse getKey(@javax.annotation.Nonnull Integer id) throws CloudKeyException {
        CloudKeyResponse<KeyResponse> localVarResp = getKeyWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * 服务账号查询卡密详情
     * 
     * @param id 卡密ID (required)
     * @return CloudKeyResponse&lt;KeyResponse&gt;
     * @throws CloudKeyException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 卡密详情 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 卡密不存在 </td><td>  -  </td></tr>
     </table>
     */
    public CloudKeyResponse<KeyResponse> getKeyWithHttpInfo(@javax.annotation.Nonnull Integer id) throws CloudKeyException {
        okhttp3.Call localVarCall = getKeyValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<KeyResponse>(){}.getType();
        return localVarCloudKeyClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 服务账号查询卡密详情 (asynchronously)
     * 
     * @param id 卡密ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws CloudKeyException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 卡密详情 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 无效的卡密 ID </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 卡密不存在 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getKeyAsync(@javax.annotation.Nonnull Integer id, final CloudKeyCallback<KeyResponse> _callback) throws CloudKeyException {

        okhttp3.Call localVarCall = getKeyValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<KeyResponse>(){}.getType();
        localVarCloudKeyClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getKeyStatus
     * @param sk 卡密值 (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws CloudKeyException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 卡密状态信息 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 缺少卡密参数 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 卡密不存在 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getKeyStatusCall(@javax.annotation.Nonnull String sk, final CloudKeyCallback _callback) throws CloudKeyException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/service/keys/status";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (sk != null) {
            localVarQueryParams.addAll(localVarCloudKeyClient.parameterToPair("sk", sk));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarCloudKeyClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarCloudKeyClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ServiceKeyAuth" };
        return localVarCloudKeyClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getKeyStatusValidateBeforeCall(@javax.annotation.Nonnull String sk, final CloudKeyCallback _callback) throws CloudKeyException {
        // verify the required parameter 'sk' is set
        if (sk == null) {
            throw new CloudKeyException("Missing the required parameter 'sk' when calling getKeyStatus(Async)");
        }

        return getKeyStatusCall(sk, _callback);

    }

    /**
     * 服务账号查询卡密状态
     * 通过 X-Service-Key 认证，根据卡密值查询状态
     * @param sk 卡密值 (required)
     * @return KeyStatusResponse
     * @throws CloudKeyException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 卡密状态信息 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 缺少卡密参数 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 卡密不存在 </td><td>  -  </td></tr>
     </table>
     */
    public KeyStatusResponse getKeyStatus(@javax.annotation.Nonnull String sk) throws CloudKeyException {
        CloudKeyResponse<KeyStatusResponse> localVarResp = getKeyStatusWithHttpInfo(sk);
        return localVarResp.getData();
    }

    /**
     * 服务账号查询卡密状态
     * 通过 X-Service-Key 认证，根据卡密值查询状态
     * @param sk 卡密值 (required)
     * @return CloudKeyResponse&lt;KeyStatusResponse&gt;
     * @throws CloudKeyException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 卡密状态信息 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 缺少卡密参数 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 卡密不存在 </td><td>  -  </td></tr>
     </table>
     */
    public CloudKeyResponse<KeyStatusResponse> getKeyStatusWithHttpInfo(@javax.annotation.Nonnull String sk) throws CloudKeyException {
        okhttp3.Call localVarCall = getKeyStatusValidateBeforeCall(sk, null);
        Type localVarReturnType = new TypeToken<KeyStatusResponse>(){}.getType();
        return localVarCloudKeyClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 服务账号查询卡密状态 (asynchronously)
     * 通过 X-Service-Key 认证，根据卡密值查询状态
     * @param sk 卡密值 (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws CloudKeyException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 卡密状态信息 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 缺少卡密参数 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 卡密不存在 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getKeyStatusAsync(@javax.annotation.Nonnull String sk, final CloudKeyCallback<KeyStatusResponse> _callback) throws CloudKeyException {

        okhttp3.Call localVarCall = getKeyStatusValidateBeforeCall(sk, _callback);
        Type localVarReturnType = new TypeToken<KeyStatusResponse>(){}.getType();
        localVarCloudKeyClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listKeys
     * @param page 页码 (optional, default to 1)
     * @param pageSize 每页数量 (optional, default to 20)
     * @param status 状态过滤: unused/used/disabled/expired (optional)
     * @param search 关键字搜索 (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws CloudKeyException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 分页卡密列表 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listKeysCall(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer pageSize, @javax.annotation.Nullable String status, @javax.annotation.Nullable String search, final CloudKeyCallback _callback) throws CloudKeyException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/service/keys";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (page != null) {
            localVarQueryParams.addAll(localVarCloudKeyClient.parameterToPair("page", page));
        }

        if (pageSize != null) {
            localVarQueryParams.addAll(localVarCloudKeyClient.parameterToPair("page_size", pageSize));
        }

        if (status != null) {
            localVarQueryParams.addAll(localVarCloudKeyClient.parameterToPair("status", status));
        }

        if (search != null) {
            localVarQueryParams.addAll(localVarCloudKeyClient.parameterToPair("search", search));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarCloudKeyClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarCloudKeyClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ServiceKeyAuth" };
        return localVarCloudKeyClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listKeysValidateBeforeCall(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer pageSize, @javax.annotation.Nullable String status, @javax.annotation.Nullable String search, final CloudKeyCallback _callback) throws CloudKeyException {
        return listKeysCall(page, pageSize, status, search, _callback);

    }

    /**
     * 服务账号查询卡密列表
     * 
     * @param page 页码 (optional, default to 1)
     * @param pageSize 每页数量 (optional, default to 20)
     * @param status 状态过滤: unused/used/disabled/expired (optional)
     * @param search 关键字搜索 (optional)
     * @return KeyListResponse
     * @throws CloudKeyException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 分页卡密列表 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public KeyListResponse listKeys(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer pageSize, @javax.annotation.Nullable String status, @javax.annotation.Nullable String search) throws CloudKeyException {
        CloudKeyResponse<KeyListResponse> localVarResp = listKeysWithHttpInfo(page, pageSize, status, search);
        return localVarResp.getData();
    }

    /**
     * 服务账号查询卡密列表
     * 
     * @param page 页码 (optional, default to 1)
     * @param pageSize 每页数量 (optional, default to 20)
     * @param status 状态过滤: unused/used/disabled/expired (optional)
     * @param search 关键字搜索 (optional)
     * @return CloudKeyResponse&lt;KeyListResponse&gt;
     * @throws CloudKeyException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 分页卡密列表 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public CloudKeyResponse<KeyListResponse> listKeysWithHttpInfo(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer pageSize, @javax.annotation.Nullable String status, @javax.annotation.Nullable String search) throws CloudKeyException {
        okhttp3.Call localVarCall = listKeysValidateBeforeCall(page, pageSize, status, search, null);
        Type localVarReturnType = new TypeToken<KeyListResponse>(){}.getType();
        return localVarCloudKeyClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 服务账号查询卡密列表 (asynchronously)
     * 
     * @param page 页码 (optional, default to 1)
     * @param pageSize 每页数量 (optional, default to 20)
     * @param status 状态过滤: unused/used/disabled/expired (optional)
     * @param search 关键字搜索 (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws CloudKeyException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 分页卡密列表 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listKeysAsync(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer pageSize, @javax.annotation.Nullable String status, @javax.annotation.Nullable String search, final CloudKeyCallback<KeyListResponse> _callback) throws CloudKeyException {

        okhttp3.Call localVarCall = listKeysValidateBeforeCall(page, pageSize, status, search, _callback);
        Type localVarReturnType = new TypeToken<KeyListResponse>(){}.getType();
        localVarCloudKeyClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateKey
     * @param id 卡密ID (required)
     * @param body 更新字段 (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws CloudKeyException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 更新成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 参数错误 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateKeyCall(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull UpdateKeyRequest body, final CloudKeyCallback _callback) throws CloudKeyException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/service/keys/{id}"
            .replace("{" + "id" + "}", localVarCloudKeyClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarCloudKeyClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarCloudKeyClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ServiceKeyAuth" };
        return localVarCloudKeyClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateKeyValidateBeforeCall(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull UpdateKeyRequest body, final CloudKeyCallback _callback) throws CloudKeyException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new CloudKeyException("Missing the required parameter 'id' when calling updateKey(Async)");
        }

        // verify the required parameter 'body' is set
        if (body == null) {
            throw new CloudKeyException("Missing the required parameter 'body' when calling updateKey(Async)");
        }

        return updateKeyCall(id, body, _callback);

    }

    /**
     * 服务账号更新卡密
     * 
     * @param id 卡密ID (required)
     * @param body 更新字段 (required)
     * @return Result
     * @throws CloudKeyException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 更新成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 参数错误 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public Result updateKey(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull UpdateKeyRequest body) throws CloudKeyException {
        CloudKeyResponse<Result> localVarResp = updateKeyWithHttpInfo(id, body);
        return localVarResp.getData();
    }

    /**
     * 服务账号更新卡密
     * 
     * @param id 卡密ID (required)
     * @param body 更新字段 (required)
     * @return CloudKeyResponse&lt;Result&gt;
     * @throws CloudKeyException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 更新成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 参数错误 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public CloudKeyResponse<Result> updateKeyWithHttpInfo(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull UpdateKeyRequest body) throws CloudKeyException {
        okhttp3.Call localVarCall = updateKeyValidateBeforeCall(id, body, null);
        Type localVarReturnType = new TypeToken<Result>(){}.getType();
        return localVarCloudKeyClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 服务账号更新卡密 (asynchronously)
     * 
     * @param id 卡密ID (required)
     * @param body 更新字段 (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws CloudKeyException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 更新成功 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 参数错误 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 服务账号密钥无效 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateKeyAsync(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull UpdateKeyRequest body, final CloudKeyCallback<Result> _callback) throws CloudKeyException {

        okhttp3.Call localVarCall = updateKeyValidateBeforeCall(id, body, _callback);
        Type localVarReturnType = new TypeToken<Result>(){}.getType();
        localVarCloudKeyClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
