/*
 * CloudKey Service Account API
 * 卡密管理系统 - 服务账号 SDK
 *
 * The version of the OpenAPI document: 1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AdjustBalanceRequest
 */
public class AdjustBalanceRequestTest {
    private final AdjustBalanceRequest model = new AdjustBalanceRequest();

    /**
     * Model tests for AdjustBalanceRequest
     */
    @Test
    public void testAdjustBalanceRequest() {
        // TODO: test AdjustBalanceRequest
    }

    /**
     * Test the property 'delta'
     */
    @Test
    public void deltaTest() {
        // TODO: test delta
    }

    /**
     * Test the property 'remark'
     */
    @Test
    public void remarkTest() {
        // TODO: test remark
    }

}
