/*
 * CloudKey Service Account API
 * 卡密管理系统 - 服务账号 SDK
 *
 * The version of the OpenAPI document: 1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AdjustBalanceResult
 */
public class AdjustBalanceResultTest {
    private final AdjustBalanceResult model = new AdjustBalanceResult();

    /**
     * Model tests for AdjustBalanceResult
     */
    @Test
    public void testAdjustBalanceResult() {
        // TODO: test AdjustBalanceResult
    }

    /**
     * Test the property 'beforeAmount'
     */
    @Test
    public void beforeAmountTest() {
        // TODO: test beforeAmount
    }

    /**
     * Test the property 'afterAmount'
     */
    @Test
    public void afterAmountTest() {
        // TODO: test afterAmount
    }

}
