/*
 * CloudKey Service Account API
 * 卡密管理系统 - 服务账号 SDK
 *
 * The version of the OpenAPI document: 1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BalanceLog
 */
public class BalanceLogTest {
    private final BalanceLog model = new BalanceLog();

    /**
     * Model tests for BalanceLog
     */
    @Test
    public void testBalanceLog() {
        // TODO: test BalanceLog
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'keyId'
     */
    @Test
    public void keyIdTest() {
        // TODO: test keyId
    }

    /**
     * Test the property 'keyAlias'
     */
    @Test
    public void keyAliasTest() {
        // TODO: test keyAlias
    }

    /**
     * Test the property 'delta'
     */
    @Test
    public void deltaTest() {
        // TODO: test delta
    }

    /**
     * Test the property 'beforeAmount'
     */
    @Test
    public void beforeAmountTest() {
        // TODO: test beforeAmount
    }

    /**
     * Test the property 'afterAmount'
     */
    @Test
    public void afterAmountTest() {
        // TODO: test afterAmount
    }

    /**
     * Test the property 'operator'
     */
    @Test
    public void operatorTest() {
        // TODO: test operator
    }

    /**
     * Test the property 'remark'
     */
    @Test
    public void remarkTest() {
        // TODO: test remark
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

}
