/*
 * CloudKey Service Account API
 * 卡密管理系统 - 服务账号 SDK
 *
 * The version of the OpenAPI document: 1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.ezzzi_y;

import java.util.Objects;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.Supplier;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-21T15:39:59.098139500+08:00[Asia/Shanghai]", comments = "Generator version: 7.24.0")
public class CloudKeyConfiguration {
  public static final String VERSION = "1.0.4";

  private static final AtomicReference<CloudKeyClient> defaultCloudKeyClient = new AtomicReference<>();
  private static volatile Supplier<CloudKeyClient> apiClientFactory = CloudKeyClient::new;

  /**
   * Get the default API client, which would be used when creating API instances without providing an API client.
   *
   * @return Default API client
   */
  public static CloudKeyClient getDefaultCloudKeyClient() {
    CloudKeyClient client = defaultCloudKeyClient.get();
    if (client == null) {
      client = defaultCloudKeyClient.updateAndGet(val -> {
        if (val != null) { // changed by another thread
          return val;
        }
        return apiClientFactory.get();
      });
    }
    return client;
  }

  /**
   * Set the default API client, which would be used when creating API instances without providing an API client.
   *
   * @param apiClient API client
   */
  public static void setDefaultCloudKeyClient(CloudKeyClient apiClient) {
    defaultCloudKeyClient.set(apiClient);
  }

  /**
   * set the callback used to create new CloudKeyClient objects
   */
  public static void setCloudKeyClientFactory(Supplier<CloudKeyClient> factory) {
    apiClientFactory = Objects.requireNonNull(factory);
  }

  private CloudKeyConfiguration() {
  }
}