/*
 * CloudKey API
 * 卡密管理系统 API 文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.ezzzi_y.model;

import com.github.ezzzi_y.model.AuthTotpSetupInitPost200ResponseAllOfData;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AuthTotpSetupInitPost200Response
 */
public class AuthTotpSetupInitPost200ResponseTest {
    private final AuthTotpSetupInitPost200Response model = new AuthTotpSetupInitPost200Response();

    /**
     * Model tests for AuthTotpSetupInitPost200Response
     */
    @Test
    public void testAuthTotpSetupInitPost200Response() {
        // TODO: test AuthTotpSetupInitPost200Response
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

}
