/*
 * CloudKey API
 * 卡密管理系统 API 文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.ezzzi_y.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AuthTotpSetupInitPost200ResponseAllOfData
 */
public class AuthTotpSetupInitPost200ResponseAllOfDataTest {
    private final AuthTotpSetupInitPost200ResponseAllOfData model = new AuthTotpSetupInitPost200ResponseAllOfData();

    /**
     * Model tests for AuthTotpSetupInitPost200ResponseAllOfData
     */
    @Test
    public void testAuthTotpSetupInitPost200ResponseAllOfData() {
        // TODO: test AuthTotpSetupInitPost200ResponseAllOfData
    }

    /**
     * Test the property 'secret'
     */
    @Test
    public void secretTest() {
        // TODO: test secret
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

}
