/*
 * CloudKey Service Account API
 * 卡密管理系统 - 服务账号 SDK
 *
 * The version of the OpenAPI document: 1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.ezzzi_y.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ConsumeResult
 */
public class ConsumeResultTest {
    private final ConsumeResult model = new ConsumeResult();

    /**
     * Model tests for ConsumeResult
     */
    @Test
    public void testConsumeResult() {
        // TODO: test ConsumeResult
    }

    /**
     * Test the property 'remainingAmount'
     */
    @Test
    public void remainingAmountTest() {
        // TODO: test remainingAmount
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'exhausted'
     */
    @Test
    public void exhaustedTest() {
        // TODO: test exhausted
    }

}
