/*
 * CloudKey Service Account API
 * 卡密管理系统 - 服务账号 SDK
 *
 * The version of the OpenAPI document: 1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.ezzzi_y.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ExportKeyItem
 */
public class ExportKeyItemTest {
    private final ExportKeyItem model = new ExportKeyItem();

    /**
     * Model tests for ExportKeyItem
     */
    @Test
    public void testExportKeyItem() {
        // TODO: test ExportKeyItem
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'keyPrefix'
     */
    @Test
    public void keyPrefixTest() {
        // TODO: test keyPrefix
    }

    /**
     * Test the property 'keySuffix'
     */
    @Test
    public void keySuffixTest() {
        // TODO: test keySuffix
    }

    /**
     * Test the property 'alias'
     */
    @Test
    public void aliasTest() {
        // TODO: test alias
    }

    /**
     * Test the property 'billingMode'
     */
    @Test
    public void billingModeTest() {
        // TODO: test billingMode
    }

    /**
     * Test the property 'initialAmount'
     */
    @Test
    public void initialAmountTest() {
        // TODO: test initialAmount
    }

    /**
     * Test the property 'remainingAmount'
     */
    @Test
    public void remainingAmountTest() {
        // TODO: test remainingAmount
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'expireAt'
     */
    @Test
    public void expireAtTest() {
        // TODO: test expireAt
    }

    /**
     * Test the property 'maxUsage'
     */
    @Test
    public void maxUsageTest() {
        // TODO: test maxUsage
    }

}
