/*
 * CloudKey API
 * 卡密管理系统 API 文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.ezzzi_y.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for HandlerCreateKeyJSON
 */
public class HandlerCreateKeyJSONTest {
    private final HandlerCreateKeyJSON model = new HandlerCreateKeyJSON();

    /**
     * Model tests for HandlerCreateKeyJSON
     */
    @Test
    public void testHandlerCreateKeyJSON() {
        // TODO: test HandlerCreateKeyJSON
    }

    /**
     * Test the property 'alias'
     */
    @Test
    public void aliasTest() {
        // TODO: test alias
    }

    /**
     * Test the property 'billingMode'
     */
    @Test
    public void billingModeTest() {
        // TODO: test billingMode
    }

    /**
     * Test the property 'expireAt'
     */
    @Test
    public void expireAtTest() {
        // TODO: test expireAt
    }

    /**
     * Test the property 'initialAmount'
     */
    @Test
    public void initialAmountTest() {
        // TODO: test initialAmount
    }

    /**
     * Test the property 'maxUsage'
     */
    @Test
    public void maxUsageTest() {
        // TODO: test maxUsage
    }

}
