/*
 * CloudKey Service Account API
 * 卡密管理系统 - 服务账号 SDK
 *
 * The version of the OpenAPI document: 1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.ezzzi_y.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for KeyStatusResult
 */
public class KeyStatusResultTest {
    private final KeyStatusResult model = new KeyStatusResult();

    /**
     * Model tests for KeyStatusResult
     */
    @Test
    public void testKeyStatusResult() {
        // TODO: test KeyStatusResult
    }

    /**
     * Test the property 'alias'
     */
    @Test
    public void aliasTest() {
        // TODO: test alias
    }

    /**
     * Test the property 'billingMode'
     */
    @Test
    public void billingModeTest() {
        // TODO: test billingMode
    }

    /**
     * Test the property 'remainingAmount'
     */
    @Test
    public void remainingAmountTest() {
        // TODO: test remainingAmount
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'usedAt'
     */
    @Test
    public void usedAtTest() {
        // TODO: test usedAt
    }

}
