/*
 * CloudKey API
 * 卡密管理系统 API 文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.ezzzi_y.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SuperTenantsPost200ResponseAllOfData
 */
public class SuperTenantsPost200ResponseAllOfDataTest {
    private final SuperTenantsPost200ResponseAllOfData model = new SuperTenantsPost200ResponseAllOfData();

    /**
     * Model tests for SuperTenantsPost200ResponseAllOfData
     */
    @Test
    public void testSuperTenantsPost200ResponseAllOfData() {
        // TODO: test SuperTenantsPost200ResponseAllOfData
    }

    /**
     * Test the property 'adminPassword'
     */
    @Test
    public void adminPasswordTest() {
        // TODO: test adminPassword
    }

    /**
     * Test the property 'adminUsername'
     */
    @Test
    public void adminUsernameTest() {
        // TODO: test adminUsername
    }

    /**
     * Test the property 'tenant'
     */
    @Test
    public void tenantTest() {
        // TODO: test tenant
    }

}
