/*
 * CloudKey API
 * 卡密管理系统 API 文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.ezzzi_y.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SuperTenantsIdResetPasswordPatch200ResponseAllOfData
 */
public class SuperTenantsIdResetPasswordPatch200ResponseAllOfDataTest {
    private final SuperTenantsIdResetPasswordPatch200ResponseAllOfData model = new SuperTenantsIdResetPasswordPatch200ResponseAllOfData();

    /**
     * Model tests for SuperTenantsIdResetPasswordPatch200ResponseAllOfData
     */
    @Test
    public void testSuperTenantsIdResetPasswordPatch200ResponseAllOfData() {
        // TODO: test SuperTenantsIdResetPasswordPatch200ResponseAllOfData
    }

    /**
     * Test the property 'newPassword'
     */
    @Test
    public void newPasswordTest() {
        // TODO: test newPassword
    }

}
