/*
 * CloudKey API
 * 卡密管理系统 API 文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.ezzzi_y.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TenantServiceAccountsPost200ResponseAllOfData
 */
public class TenantServiceAccountsPost200ResponseAllOfDataTest {
    private final TenantServiceAccountsPost200ResponseAllOfData model = new TenantServiceAccountsPost200ResponseAllOfData();

    /**
     * Model tests for TenantServiceAccountsPost200ResponseAllOfData
     */
    @Test
    public void testTenantServiceAccountsPost200ResponseAllOfData() {
        // TODO: test TenantServiceAccountsPost200ResponseAllOfData
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'isActive'
     */
    @Test
    public void isActiveTest() {
        // TODO: test isActive
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'rawKey'
     */
    @Test
    public void rawKeyTest() {
        // TODO: test rawKey
    }

}
