/*
 * CloudKey Service Account API
 * 卡密管理系统 - 服务账号 SDK
 *
 * The version of the OpenAPI document: 1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.CloudKeyException;
import org.openapitools.client.model.BalanceLogListResponse;
import org.openapitools.client.model.ExportBalanceLogsResponse;
import org.openapitools.client.model.Result;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BalanceLogsApi
 */
@Disabled
public class BalanceLogsApiTest {

    private final BalanceLogsApi api = new BalanceLogsApi();

    /**
     * 导出额度流转日志
     *
     * @throws CloudKeyException if the Api call fails
     */
    @Test
    public void exportBalanceLogsTest() throws CloudKeyException {
        Long keyId = null;
        String operator = null;
        String startTime = null;
        String endTime = null;
        ExportBalanceLogsResponse response = api.exportBalanceLogs(keyId, operator, startTime, endTime);
        // TODO: test validations
    }

    /**
     * 查询额度流转日志
     *
     * @throws CloudKeyException if the Api call fails
     */
    @Test
    public void listBalanceLogsTest() throws CloudKeyException {
        Integer page = null;
        Integer pageSize = null;
        Long keyId = null;
        String operator = null;
        String startTime = null;
        String endTime = null;
        BalanceLogListResponse response = api.listBalanceLogs(page, pageSize, keyId, operator, startTime, endTime);
        // TODO: test validations
    }

}
