/*
 * CloudKey API
 * 卡密管理系统 API 文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.ezzzi_y.api;

import com.github.ezzzi_y.ApiException;
import com.github.ezzzi_y.model.HandlerResponse;
import com.github.ezzzi_y.model.HandlerServiceConsumeReq;
import com.github.ezzzi_y.model.ServiceKeysGet200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApiApi
 */
@Disabled
public class ApiApiTest {

    private final ApiApi api = new ApiApi();

    /**
     * 服务账号扣减卡密额度
     *
     * 通过 X-Service-Key 认证，扣减指定卡密的剩余额度
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void serviceKeysConsumePostTest() throws ApiException {
        HandlerServiceConsumeReq body = null;
        HandlerResponse response = api.serviceKeysConsumePost(body);
        // TODO: test validations
    }

    /**
     * 服务账号导出卡密（文本格式）
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void serviceKeysExportGetTest() throws ApiException {
        HandlerResponse response = api.serviceKeysExportGet();
        // TODO: test validations
    }

    /**
     * 服务账号导出卡密（JSON 格式）
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void serviceKeysExportJsonGetTest() throws ApiException {
        HandlerResponse response = api.serviceKeysExportJsonGet();
        // TODO: test validations
    }

    /**
     * 服务账号查询卡密列表
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void serviceKeysGetTest() throws ApiException {
        Integer page = null;
        Integer pageSize = null;
        String status = null;
        String search = null;
        ServiceKeysGet200Response response = api.serviceKeysGet(page, pageSize, status, search);
        // TODO: test validations
    }

    /**
     * 服务账号删除卡密
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void serviceKeysIdDeleteTest() throws ApiException {
        Integer id = null;
        HandlerResponse response = api.serviceKeysIdDelete(id);
        // TODO: test validations
    }

    /**
     * 服务账号禁用卡密
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void serviceKeysIdDisablePatchTest() throws ApiException {
        Integer id = null;
        HandlerResponse response = api.serviceKeysIdDisablePatch(id);
        // TODO: test validations
    }

    /**
     * 服务账号启用卡密
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void serviceKeysIdEnablePatchTest() throws ApiException {
        Integer id = null;
        HandlerResponse response = api.serviceKeysIdEnablePatch(id);
        // TODO: test validations
    }

    /**
     * 服务账号查询卡密详情
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void serviceKeysIdGetTest() throws ApiException {
        Integer id = null;
        HandlerResponse response = api.serviceKeysIdGet(id);
        // TODO: test validations
    }

    /**
     * 服务账号更新卡密
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void serviceKeysIdPatchTest() throws ApiException {
        Integer id = null;
        Object body = null;
        HandlerResponse response = api.serviceKeysIdPatch(id, body);
        // TODO: test validations
    }

    /**
     * 服务账号创建卡密
     *
     * 通过 X-Service-Key 认证，服务账号创建卡密
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void serviceKeysPostTest() throws ApiException {
        Object body = null;
        HandlerResponse response = api.serviceKeysPost(body);
        // TODO: test validations
    }

    /**
     * 服务账号查询卡密状态
     *
     * 通过 X-Service-Key 认证，根据卡密值查询状态
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void serviceKeysStatusGetTest() throws ApiException {
        String sk = null;
        HandlerResponse response = api.serviceKeysStatusGet(sk);
        // TODO: test validations
    }

}
