/*
 * CloudKey API
 * 卡密管理系统 API 文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.ezzzi_y.api;

import com.github.ezzzi_y.ApiException;
import com.github.ezzzi_y.model.AuthTotpConfirmInitPost200Response;
import com.github.ezzzi_y.model.AuthTotpSetupInitPost200Response;
import com.github.ezzzi_y.model.HandlerConsumeRequest;
import com.github.ezzzi_y.model.HandlerCreateKeyJSON;
import com.github.ezzzi_y.model.HandlerLoginRequest;
import com.github.ezzzi_y.model.HandlerResponse;
import com.github.ezzzi_y.model.HandlerVerify2FARequest;
import com.github.ezzzi_y.model.ServiceKeysGet200Response;
import com.github.ezzzi_y.model.SuperTenantsIdResetPasswordPatch200Response;
import com.github.ezzzi_y.model.SuperTenantsPost200Response;
import com.github.ezzzi_y.model.TenantServiceAccountsPost200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Disabled
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * 用户名密码登录
     *
     * 用户名密码验证，成功后返回 pre_auth_token 用于后续 TOTP 验证
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void authLoginPostTest() throws ApiException {
        HandlerLoginRequest body = null;
        HandlerResponse response = api.authLoginPost(body);
        // TODO: test validations
    }

    /**
     * 确认 TOTP 绑定并登录
     *
     * 首次登录用户确认 TOTP 绑定后自动登录，返回 JWT
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void authTotpConfirmInitPostTest() throws ApiException {
        Object body = null;
        AuthTotpConfirmInitPost200Response response = api.authTotpConfirmInitPost(body);
        // TODO: test validations
    }

    /**
     * 初始化 TOTP 绑定
     *
     * 首次登录用户生成 TOTP 密钥，需先通过密码验证获取 user_id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void authTotpSetupInitPostTest() throws ApiException {
        Object body = null;
        AuthTotpSetupInitPost200Response response = api.authTotpSetupInitPost(body);
        // TODO: test validations
    }

    /**
     * TOTP 二次验证
     *
     * 登录成功后使用 pre_auth_token + TOTP 验证码完成认证，返回 JWT
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void authVerify2faPostTest() throws ApiException {
        HandlerVerify2FARequest body = null;
        AuthTotpConfirmInitPost200Response response = api.authVerify2faPost(body);
        // TODO: test validations
    }

    /**
     * 获取系统配置
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void superConfigsGetTest() throws ApiException {
        HandlerResponse response = api.superConfigsGet();
        // TODO: test validations
    }

    /**
     * 更新系统配置
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void superConfigsPutTest() throws ApiException {
        Object body = null;
        HandlerResponse response = api.superConfigsPut(body);
        // TODO: test validations
    }

    /**
     * 登录日志
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void superLoginLogsGetTest() throws ApiException {
        Integer page = null;
        Integer pageSize = null;
        ServiceKeysGet200Response response = api.superLoginLogsGet(page, pageSize);
        // TODO: test validations
    }

    /**
     * 修改密码
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void superPasswordPutTest() throws ApiException {
        Object body = null;
        HandlerResponse response = api.superPasswordPut(body);
        // TODO: test validations
    }

    /**
     * 获取当前用户信息
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void superProfileGetTest() throws ApiException {
        HandlerResponse response = api.superProfileGet();
        // TODO: test validations
    }

    /**
     * 租户列表
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void superTenantsGetTest() throws ApiException {
        HandlerResponse response = api.superTenantsGet();
        // TODO: test validations
    }

    /**
     * 租户详情
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void superTenantsIdGetTest() throws ApiException {
        Integer id = null;
        HandlerResponse response = api.superTenantsIdGet(id);
        // TODO: test validations
    }

    /**
     * 更新租户
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void superTenantsIdPatchTest() throws ApiException {
        Integer id = null;
        Object body = null;
        HandlerResponse response = api.superTenantsIdPatch(id, body);
        // TODO: test validations
    }

    /**
     * 重置租户管理员密码
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void superTenantsIdResetPasswordPatchTest() throws ApiException {
        Integer id = null;
        SuperTenantsIdResetPasswordPatch200Response response = api.superTenantsIdResetPasswordPatch(id);
        // TODO: test validations
    }

    /**
     * 创建租户
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void superTenantsPostTest() throws ApiException {
        Object body = null;
        SuperTenantsPost200Response response = api.superTenantsPost(body);
        // TODO: test validations
    }

    /**
     * 确认 TOTP 绑定
     *
     * 已登录用户输入验证码确认 TOTP 绑定
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void superTotpConfirmPostTest() throws ApiException {
        Object body = null;
        HandlerResponse response = api.superTotpConfirmPost(body);
        // TODO: test validations
    }

    /**
     * 生成 TOTP 密钥
     *
     * 已登录用户生成新的 TOTP 密钥，用于更换验证器
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void superTotpSetupPostTest() throws ApiException {
        AuthTotpSetupInitPost200Response response = api.superTotpSetupPost();
        // TODO: test validations
    }

    /**
     * 扣减卡密额度
     *
     * 扣减指定卡密的剩余额度
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tenantKeysConsumePostTest() throws ApiException {
        HandlerConsumeRequest body = null;
        HandlerResponse response = api.tenantKeysConsumePost(body);
        // TODO: test validations
    }

    /**
     * 导出卡密（文本格式）
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tenantKeysExportGetTest() throws ApiException {
        HandlerResponse response = api.tenantKeysExportGet();
        // TODO: test validations
    }

    /**
     * 导出卡密（JSON 格式）
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tenantKeysExportJsonGetTest() throws ApiException {
        HandlerResponse response = api.tenantKeysExportJsonGet();
        // TODO: test validations
    }

    /**
     * 卡密列表
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tenantKeysGetTest() throws ApiException {
        Integer page = null;
        Integer pageSize = null;
        String status = null;
        String search = null;
        ServiceKeysGet200Response response = api.tenantKeysGet(page, pageSize, status, search);
        // TODO: test validations
    }

    /**
     * 删除卡密
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tenantKeysIdDeleteTest() throws ApiException {
        Integer id = null;
        HandlerResponse response = api.tenantKeysIdDelete(id);
        // TODO: test validations
    }

    /**
     * 禁用卡密
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tenantKeysIdDisablePatchTest() throws ApiException {
        Integer id = null;
        HandlerResponse response = api.tenantKeysIdDisablePatch(id);
        // TODO: test validations
    }

    /**
     * 启用卡密
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tenantKeysIdEnablePatchTest() throws ApiException {
        Integer id = null;
        HandlerResponse response = api.tenantKeysIdEnablePatch(id);
        // TODO: test validations
    }

    /**
     * 卡密详情
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tenantKeysIdGetTest() throws ApiException {
        Integer id = null;
        HandlerResponse response = api.tenantKeysIdGet(id);
        // TODO: test validations
    }

    /**
     * 更新卡密
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tenantKeysIdPatchTest() throws ApiException {
        Integer id = null;
        Object body = null;
        HandlerResponse response = api.tenantKeysIdPatch(id, body);
        // TODO: test validations
    }

    /**
     * 创建卡密
     *
     * 租户管理员创建新卡密，需业务状态正常
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tenantKeysPostTest() throws ApiException {
        HandlerCreateKeyJSON body = null;
        HandlerResponse response = api.tenantKeysPost(body);
        // TODO: test validations
    }

    /**
     * 查询卡密状态
     *
     * 根据卡密值查询卡密状态，不扣减额度
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tenantKeysStatusGetTest() throws ApiException {
        String sk = null;
        HandlerResponse response = api.tenantKeysStatusGet(sk);
        // TODO: test validations
    }

    /**
     * 登录日志
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tenantLoginLogsGetTest() throws ApiException {
        Integer page = null;
        Integer pageSize = null;
        ServiceKeysGet200Response response = api.tenantLoginLogsGet(page, pageSize);
        // TODO: test validations
    }

    /**
     * 修改密码
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tenantPasswordPutTest() throws ApiException {
        Object body = null;
        HandlerResponse response = api.tenantPasswordPut(body);
        // TODO: test validations
    }

    /**
     * 获取当前用户信息
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tenantProfileGetTest() throws ApiException {
        HandlerResponse response = api.tenantProfileGet();
        // TODO: test validations
    }

    /**
     * 服务账号列表
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tenantServiceAccountsGetTest() throws ApiException {
        HandlerResponse response = api.tenantServiceAccountsGet();
        // TODO: test validations
    }

    /**
     * 删除服务账号
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tenantServiceAccountsIdDeleteTest() throws ApiException {
        Integer id = null;
        HandlerResponse response = api.tenantServiceAccountsIdDelete(id);
        // TODO: test validations
    }

    /**
     * 启用/禁用服务账号
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tenantServiceAccountsIdTogglePatchTest() throws ApiException {
        Integer id = null;
        Object body = null;
        HandlerResponse response = api.tenantServiceAccountsIdTogglePatch(id, body);
        // TODO: test validations
    }

    /**
     * 创建服务账号
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tenantServiceAccountsPostTest() throws ApiException {
        Object body = null;
        TenantServiceAccountsPost200Response response = api.tenantServiceAccountsPost(body);
        // TODO: test validations
    }

    /**
     * 仪表盘数据
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tenantStatsDashboardGetTest() throws ApiException {
        HandlerResponse response = api.tenantStatsDashboardGet();
        // TODO: test validations
    }

    /**
     * 卡密概览统计
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tenantStatsOverviewGetTest() throws ApiException {
        String startDate = null;
        String endDate = null;
        HandlerResponse response = api.tenantStatsOverviewGet(startDate, endDate);
        // TODO: test validations
    }

    /**
     * 热门卡密
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tenantStatsTopKeysGetTest() throws ApiException {
        String startDate = null;
        String endDate = null;
        HandlerResponse response = api.tenantStatsTopKeysGet(startDate, endDate);
        // TODO: test validations
    }

    /**
     * 调用趋势
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tenantStatsTrendsGetTest() throws ApiException {
        String period = null;
        String startDate = null;
        String endDate = null;
        HandlerResponse response = api.tenantStatsTrendsGet(period, startDate, endDate);
        // TODO: test validations
    }

    /**
     * 确认 TOTP 绑定
     *
     * 已登录用户输入验证码确认 TOTP 绑定
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tenantTotpConfirmPostTest() throws ApiException {
        Object body = null;
        HandlerResponse response = api.tenantTotpConfirmPost(body);
        // TODO: test validations
    }

    /**
     * 生成 TOTP 密钥
     *
     * 已登录用户生成新的 TOTP 密钥，用于更换验证器
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tenantTotpSetupPostTest() throws ApiException {
        AuthTotpSetupInitPost200Response response = api.tenantTotpSetupPost();
        // TODO: test validations
    }

    /**
     * 导出使用日志
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tenantUsageLogsExportGetTest() throws ApiException {
        String keyAlias = null;
        String ip = null;
        String startTime = null;
        String endTime = null;
        HandlerResponse response = api.tenantUsageLogsExportGet(keyAlias, ip, startTime, endTime);
        // TODO: test validations
    }

    /**
     * 使用日志列表
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tenantUsageLogsGetTest() throws ApiException {
        Integer page = null;
        Integer pageSize = null;
        String keyAlias = null;
        String ip = null;
        String startTime = null;
        String endTime = null;
        ServiceKeysGet200Response response = api.tenantUsageLogsGet(page, pageSize, keyAlias, ip, startTime, endTime);
        // TODO: test validations
    }

}
