/*
 * CloudKey Service Account API
 * 卡密管理系统 - 服务账号 SDK
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.ezzzi_y.api;

import com.github.ezzzi_y.CloudKeyException;
import com.github.ezzzi_y.model.ConsumeRequest;
import com.github.ezzzi_y.model.KeyListResponse;
import com.github.ezzzi_y.model.Result;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ServiceKeysApi
 */
@Disabled
public class ServiceKeysApiTest {

    private final ServiceKeysApi api = new ServiceKeysApi();

    /**
     * 服务账号扣减卡密额度
     *
     * 通过 X-Service-Key 认证，扣减指定卡密的剩余额度
     *
     * @throws CloudKeyException if the Api call fails
     */
    @Test
    public void consumeKeyTest() throws CloudKeyException {
        ConsumeRequest body = null;
        Result response = api.consumeKey(body);
        // TODO: test validations
    }

    /**
     * 服务账号创建卡密
     *
     * 通过 X-Service-Key 认证，服务账号创建卡密
     *
     * @throws CloudKeyException if the Api call fails
     */
    @Test
    public void createKeyTest() throws CloudKeyException {
        Object body = null;
        Result response = api.createKey(body);
        // TODO: test validations
    }

    /**
     * 服务账号删除卡密
     *
     * @throws CloudKeyException if the Api call fails
     */
    @Test
    public void deleteKeyTest() throws CloudKeyException {
        Integer id = null;
        Result response = api.deleteKey(id);
        // TODO: test validations
    }

    /**
     * 服务账号禁用卡密
     *
     * @throws CloudKeyException if the Api call fails
     */
    @Test
    public void disableKeyTest() throws CloudKeyException {
        Integer id = null;
        Result response = api.disableKey(id);
        // TODO: test validations
    }

    /**
     * 服务账号启用卡密
     *
     * @throws CloudKeyException if the Api call fails
     */
    @Test
    public void enableKeyTest() throws CloudKeyException {
        Integer id = null;
        Result response = api.enableKey(id);
        // TODO: test validations
    }

    /**
     * 服务账号导出卡密（文本格式）
     *
     * @throws CloudKeyException if the Api call fails
     */
    @Test
    public void exportKeysTest() throws CloudKeyException {
        Result response = api.exportKeys();
        // TODO: test validations
    }

    /**
     * 服务账号导出卡密（JSON 格式）
     *
     * @throws CloudKeyException if the Api call fails
     */
    @Test
    public void exportKeysJsonTest() throws CloudKeyException {
        Result response = api.exportKeysJson();
        // TODO: test validations
    }

    /**
     * 服务账号查询卡密详情
     *
     * @throws CloudKeyException if the Api call fails
     */
    @Test
    public void getKeyTest() throws CloudKeyException {
        Integer id = null;
        Result response = api.getKey(id);
        // TODO: test validations
    }

    /**
     * 服务账号查询卡密状态
     *
     * 通过 X-Service-Key 认证，根据卡密值查询状态
     *
     * @throws CloudKeyException if the Api call fails
     */
    @Test
    public void getKeyStatusTest() throws CloudKeyException {
        String sk = null;
        Result response = api.getKeyStatus(sk);
        // TODO: test validations
    }

    /**
     * 服务账号查询卡密列表
     *
     * @throws CloudKeyException if the Api call fails
     */
    @Test
    public void listKeysTest() throws CloudKeyException {
        Integer page = null;
        Integer pageSize = null;
        String status = null;
        String search = null;
        KeyListResponse response = api.listKeys(page, pageSize, status, search);
        // TODO: test validations
    }

    /**
     * 服务账号更新卡密
     *
     * @throws CloudKeyException if the Api call fails
     */
    @Test
    public void updateKeyTest() throws CloudKeyException {
        Integer id = null;
        Object body = null;
        Result response = api.updateKey(id, body);
        // TODO: test validations
    }

}
